### ISSUE TITLE
NoMethodError: infer_spec_type_from_file_location!

### ISSUE THREAD

**Issue by ebbnormal** [rspec/rspec-rails#1126]
I am having trouble with my RSpec 3.0.2. I have in my `spec_helper.rb` file the following line to explicitly use the directory structure to interpret my controller_spec as for a controller. 

`RSpec.configure do |config|
   config.infer_spec_type_from_file_location!
 end`

However I end up getting this error when I run `bundle exec rspec`: 

`/spec/spec_helper.rb:6:in block in <top (required)>: undefined method infer_spec_type_from_file_location!' for #<RSpec::Core::Configuration:0x00000101e7c370> (NoMethodError)`

**Comment by pmontrasio** [comment]
I'm getting this with rspec-rails 3.5.1 and Rails 5.0.0

I do have rspec-rails installed

```
group :development, :test do
  gem 'rspec-rails', '~> 3.5'
  ...
end
```

and 

```
$ bundle show | grep rspec
  * rspec-core (3.5.2)
  * rspec-expectations (3.5.0)
  * rspec-mocks (3.5.0)
  * rspec-rails (3.5.1)
  * rspec-support (3.5.0)
```

I generated ```spec/spec_helper.rb``` with ```rails generate rspec:install``` after the ```bundle install```, then I added

```
RSpec.configure do |config|
  config.infer_spec_type_from_file_location!
  ...
end
```

And now

```
$ bundle exec rails spec
/home/me/.rvm/rubies/ruby-2.3.1/bin/ruby -I/home/me/.rvm/gems/ruby-2.3.1@myapp/gems/rspec-core-3.5.2/lib:/home/me/.rvm/gems/ruby-2.3.1@myapp/gems/rspec-support-3.5.0/lib /home/me/.rvm/gems/ruby-2.3.1@myapp/gems/rspec-core-3.5.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
/home/me/myapp/myapp-web/spec/spec_helper.rb:50:in `block in <top (required)>': undefined method `infer_spec_type_from_file_location!' for #<RSpec::Core::Configuration:0x00000002d59998> (NoMethodError)
	from /home/me/.rvm/gems/ruby-2.3.1@myapp/gems/rspec-core-3.5.2/lib/rspec/core.rb:97:in `configure'
	from /home/me/myapp/myapp-web/spec/spec_helper.rb:19:in `<top (required)>'
	from /home/me/.rvm/gems/ruby-2.3.1@myapp/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1394:in `require'
	from /home/me/.rvm/gems/ruby-2.3.1@myapp/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1394:in `block in requires='
	from /home/me/.rvm/gems/ruby-2.3.1@myapp/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1394:in `each'
	from /home/me/.rvm/gems/ruby-2.3.1@myapp/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1394:in `requires='
	from /home/me/.rvm/gems/ruby-2.3.1@myapp/gems/rspec-core-3.5.2/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
	from /home/me/.rvm/gems/ruby-2.3.1@myapp/gems/rspec-core-3.5.2/lib/rspec/core/configuration_options.rb:111:in `each'
	from /home/me/.rvm/gems/ruby-2.3.1@myapp/gems/rspec-core-3.5.2/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
	from /home/me/.rvm/gems/ruby-2.3.1@myapp/gems/rspec-core-3.5.2/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /home/me/.rvm/gems/ruby-2.3.1@myapp/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:99:in `setup'
	from /home/me/.rvm/gems/ruby-2.3.1@myapp/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:86:in `run'
	from /home/me/.rvm/gems/ruby-2.3.1@myapp/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:71:in `run'
	from /home/me/.rvm/gems/ruby-2.3.1@myapp/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:45:in `invoke'
	from /home/me/.rvm/gems/ruby-2.3.1@myapp/gems/rspec-core-3.5.2/exe/rspec:4:in `<main>'
/home/me/.rvm/rubies/ruby-2.3.1/bin/ruby -I/home/me/.rvm/gems/ruby-2.3.1@myapp/gems/rspec-core-3.5.2/lib:/home/me/.rvm/gems/ruby-2.3.1@myapp/gems/rspec-support-3.5.0/lib /home/me/.rvm/gems/ruby-2.3.1@myapp/gems/rspec-core-3.5.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

**Comment by JonRowe** [comment]
@pmontrasio put it in your `rails_helper` instead

**Comment by pmontrasio** [comment]
@JonRowe thanks, you pointed me to my mistake.

Actually that line was already in ```rails_helper``` (courtesy of ```rails generate rspec:install``` I guess) but I didn't notice it. I added that line to ```spec_helper``` and it doesn't work there because it's missing ```require 'rspec/rails'```.
