### ISSUE TITLE
Build is failing due to warning output on older Rails

### ISSUE THREAD

**Issue by cupakromer** [rspec/rspec-rails#1341]
The build is now failing due to warning output on older Rails versions:

```
  1) RSpec::Rails::RoutingExampleGroup named routes delegates them to the route_set
     Failure/Error: Unable to find matching line from backtrace
     RuntimeError:
       Warnings were generated: WARNING: `#<Class:0x7fc12ab2bd60>#fixture_table_names` is being redefined at /home/travis/build/rspec/bundle/ruby/1.8/gems/activesupport-3.1.12/lib/active_support/core_ext/class/attribute.rb:87:in `fixture_table_names='. The original definition will never be used and can be removed.
       WARNING: `#<Class:0x7fc12ab2bd60>#use_transactional_fixtures` is being redefined at /home/travis/build/rspec/bundle/ruby/1.8/gems/activesupport-3.1.12/lib/active_support/core_ext/class/attribute.rb:87:in `use_transactional_fixtures='. The original definition will never be used and can be removed.
       WARNING: `#<Class:0x7fc12ab2bd60>#use_instantiated_fixtures` is being redefined at /home/travis/build/rspec/bundle/ruby/1.8/gems/activesupport-3.1.12/lib/active_support/core_ext/class/attribute.rb:87:in `use_instantiated_fixtures='. The original definition will never be used and can be removed.
       WARNING: `#<Class:0x7fc12ab2bd60>#pre_loaded_fixtures` is being redefined at /home/travis/build/rspec/bundle/ruby/1.8/gems/activesupport-3.1.12/lib/active_support/core_ext/class/attribute.rb:87:in `pre_loaded_fixtures='. The original definition will never be used and can be removed.
       WARNING: `#<Class:0x7fc12ab2bd60>#fixture_class_names` is being redefined at /home/travis/build/rspec/bundle/ruby/1.8/gems/activesupport-3.1.12/lib/active_support/core_ext/class/attribute.rb:87:in `fixture_class_names='. The original definition will never be used and can be removed.
       WARNING: `#<Class:0x7fc12ab2bd60>#fixture_path` is being redefined at /home/travis/build/rspec/bundle/ruby/1.8/gems/activesupport-3.1.12/lib/active_support/core_ext/class/attribute.rb:87:in `fixture_path='. The original definition will never be used and can be removed.
       WARNING: `#<Class:0x7fc12ab2bd60>#use_transactional_fixtures` is being redefined at /home/travis/build/rspec/bundle/ruby/1.8/gems/activesupport-3.1.12/lib/active_support/core_ext/class/attribute.rb:87:in `use_transactional_fixtures='. The original definition will never be used and can be removed.
       WARNING: `#<Class:0x7fc12ab2bd60>#use_instantiated_fixtures` is being redefined at /home/travis/build/rspec/bundle/ruby/1.8/gems/activesupport-3.1.12/lib/active_support/core_ext/class/attribute.rb:87:in `use_instantiated_fixtures='. The original definition will never be used and can be removed.
     # /home/travis/build/rspec/rspec-support/lib/rspec/support/spec/stderr_splitter.rb:54:in `send'
     # /home/travis/build/rspec/rspec-support/lib/rspec/support/spec/stderr_splitter.rb:54:in `verify_example!'
     # /home/travis/build/rspec/rspec-support/lib/rspec/support/spec.rb:25
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/example.rb:355:in `instance_exec'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/example.rb:355:in `instance_exec_with_rescue'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/hooks.rb:364:in `run'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/hooks.rb:517:in `run_owned_hooks_for'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/hooks.rb:516:in `each'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/hooks.rb:516:in `run_owned_hooks_for'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/hooks.rb:603:in `run_example_hooks_for'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/hooks.rb:602:in `each'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/hooks.rb:602:in `__send__'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/hooks.rb:602:in `run_example_hooks_for'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/hooks.rb:473:in `run'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/example.rb:421:in `run_after_example'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/example.rb:221:in `run'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/example.rb:414:in `with_around_and_singleton_context_hooks'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/example.rb:372:in `with_around_example_hooks'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/hooks.rb:474:in `run'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/hooks.rb:612:in `run_around_example_hooks_for'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/hooks.rb:474:in `run'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/example.rb:372:in `with_around_example_hooks'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/example.rb:414:in `with_around_and_singleton_context_hooks'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/example.rb:203:in `run'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/example_group.rb:559:in `run_examples'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/example_group.rb:555:in `map'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/example_group.rb:555:in `run_examples'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/example_group.rb:523:in `run'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/example_group.rb:524:in `run'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/example_group.rb:524:in `map'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/example_group.rb:524:in `run'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/runner.rb:112:in `run_specs'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/runner.rb:112:in `map'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/runner.rb:112:in `run_specs'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/configuration.rb:1594:in `with_suite_hooks'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/runner.rb:111:in `run_specs'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/reporter.rb:70:in `report'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/runner.rb:110:in `run_specs'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/runner.rb:86:in `run'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/runner.rb:70:in `run'
     # /home/travis/build/rspec/rspec-core/lib/rspec/core/runner.rb:38:in `invoke'
     # /home/travis/build/rspec/rspec-core/exe/rspec:4
     # bin/rspec:16:in `load'
     # bin/rspec:16
```

For an example ref: https://travis-ci.org/rspec/rspec-rails/jobs/54809817

**Comment by cupakromer** [comment]
Working on this now.

**Comment by cupakromer** [comment]
Hmm, not sure if this is Rails or us. I know the error is coming from our helper, but when I start digging into where those methods get defined it seems to all be in Rails.

/cc @samphippen

**Comment by samphippen** [comment]
I've literally no idea. Sorry

**Comment by JonRowe** [comment]
Backtrace looks all rails to me

**Comment by samphippen** [comment]
@cupakromer I'm going to take a look at this this week.

**Comment by cupakromer** [comment]
Things seem to be passing now. Seems like it was some updates to the support setup for specs. Closing.
