### ISSUE TITLE
`invalid option: --default_path` from when running `rspec` after bare-bone install of Rails & rspec-rails

### ISSUE THREAD

**Issue by stefanhendriks** [rspec/rspec-rails#1356]
I have seen this issue being tackled before, and I tried the solutions (by trying to skip Autorun).

Scenario:
I use ZSH (`zsh 5.0.5`)
I use RVM (`rvm 1.26.11`):
Ruby version: `ruby 2.0.0p195 (2013-05-14 revision 40734) [x86_64-darwin14.3.0]` 
Gemset name `bla`

I create a new directory, then do:
`gem install rails` (installs Rails 4.2.1)
`rails new FooBar` (creates new project)
`cd FooBar`
Add `gem 'rspec-rails'` to `group :development, :test`
`bundle`

Then:
`rspec` gives:
```
Invalid option: --default_path

Please use --help for a listing of valid options
```

or:
`rake spec` gives:
```
/Users/shendriks/.rvm/rubies/ruby-2.0.0-p195/bin/ruby -I/Users/shendriks/.rvm/gems/ruby-2.0.0-p195@bla/gems/rspec-core-3.2.3/lib:/Users/shendriks/.rvm/gems/ruby-2.0.0-p195@bla/gems/rspec-support-3.2.2/lib /Users/shendriks/.rvm/gems/ruby-2.0.0-p195@bla/gems/rspec-core-3.2.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
invalid option: --default_path

Please use --help for a listing of valid options
/Users/shendriks/.rvm/rubies/ruby-2.0.0-p195/bin/ruby -I/Users/shendriks/.rvm/gems/ruby-2.0.0-p195@bla/gems/rspec-core-3.2.3/lib:/Users/shendriks/.rvm/gems/ruby-2.0.0-p195@bla/gems/rspec-support-3.2.2/lib /Users/shendriks/.rvm/gems/ruby-2.0.0-p195@bla/gems/rspec-core-3.2.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

`bundle show` gives:
```
Gems included by the bundle:
  * actionmailer (4.2.1)
  * actionpack (4.2.1)
  * actionview (4.2.1)
  * activejob (4.2.1)
  * activemodel (4.2.1)
  * activerecord (4.2.1)
  * activesupport (4.2.1)
  * arel (6.0.0)
  * binding_of_caller (0.7.2)
  * builder (3.2.2)
  * bundler (1.9.4)
  * byebug (4.0.5)
  * coffee-rails (4.1.0)
  * coffee-script (2.4.1)
  * coffee-script-source (1.9.1.1)
  * columnize (0.9.0)
  * debug_inspector (0.0.2)
  * diff-lcs (1.2.5)
  * erubis (2.7.0)
  * execjs (2.5.2)
  * globalid (0.3.5)
  * i18n (0.7.0)
  * jbuilder (2.2.13)
  * jquery-rails (4.0.3)
  * json (1.8.2)
  * loofah (2.0.1)
  * mail (2.6.3)
  * mime-types (2.4.3)
  * mini_portile (0.6.2)
  * minitest (5.6.0)
  * multi_json (1.11.0)
  * nokogiri (1.6.6.2)
  * rack (1.6.0)
  * rack-test (0.6.3)
  * rails (4.2.1)
  * rails-deprecated_sanitizer (1.0.3)
  * rails-dom-testing (1.0.6)
  * rails-html-sanitizer (1.0.2)
  * railties (4.2.1)
  * rake (10.4.2)
  * rdoc (4.2.0)
  * rspec-core (3.2.3)
  * rspec-expectations (3.2.1)
  * rspec-mocks (3.2.1)
  * rspec-rails (3.2.1)
  * rspec-support (3.2.2)
  * sass (3.4.13)
  * sass-rails (5.0.3)
  * sdoc (0.4.1)
  * spring (1.3.4)
  * sprockets (3.0.1)
  * sprockets-rails (2.2.4)
  * sqlite3 (1.3.10)
  * thor (0.19.1)
  * thread_safe (0.3.5)
  * tilt (1.4.1)
  * turbolinks (2.5.3)
  * tzinfo (1.2.2)
  * uglifier (2.7.1)
  * web-console (2.1.2)
```

If I understand correctly from https://github.com/rspec/rspec-rails/issues/1312 it seems to happen due `Test::Unit` or `Minitest` (wrapping Test::Unit) to be loaded.

As you can see I don't do anything special yet and this happens. I have been a while out of ruby (and rails with rspec) development but afaik it used to work out of the box with no hassle?

**Comment by stefanhendriks** [comment]
adding a `raise` within `/Users/shendriks/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/test/unit.rb` does not seem to have any effect. Although I expected to at least see the gem including/using this would be affected.

**Comment by stefanhendriks** [comment]
Tried to reduce scope further and still able to reproduce only with `rspec` installed (not even `rspec-rails`). This makes this issue redundant so I will close this (not an issue, but just on my machine I'm afraid).

**Comment by myronmarston** [comment]
Can you push your repro to a github repository?  Then one of us can clone it and try it and see if we can repro.

**Comment by stefanhendriks** [comment]
Sure thing: https://github.com/stefanhendriks/rspec-invalid-option-1356

**Comment by myronmarston** [comment]
Thanks for pushing that repo up...but I can't repro with it:

```
➜  rspec-invalid-option-1356 git:(master) ruby -v
ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-darwin12.5.0]
➜  rspec-invalid-option-1356 git:(master) bundle
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Using diff-lcs 1.2.5
Installing rspec-support 3.2.2
Installing rspec-core 3.2.3
Installing rspec-expectations 3.2.1
Installing rspec-mocks 3.2.1
Installing rspec 3.2.0
Using bundler 1.9.2
Bundle complete! 1 Gemfile dependency, 7 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
➜  rspec-invalid-option-1356 git:(master) bundle exec rspec
No examples found.


Finished in 0.00019 seconds (files took 0.05338 seconds to load)
0 examples, 0 failures

➜  rspec-invalid-option-1356 git:(master)
```

One thing that could cause the issue on your machine but not mine is a difference in environment variables.  For example, if you have `RUBYOPT="-rtest/unit"` in your environment, it's going to load test unit.  Can you use `printenv` (or whatever the equivalent is for whatever shell you are using) and paste your environment here?  (Sans any credentials or other sensitive things in your environment, of course).

**Comment by stefanhendriks** [comment]
Interestingly, when I downgrade to `rspec` version `2.14.1` it works on my machine.

**Comment by stefanhendriks** [comment]
It seems to start failing at version `3.0.0` , when running `2.99.0` I get this result:

```
No examples found.
No examples found.



Deprecation Warnings:

The `--default_path` option is deprecated. Use --default-path instead.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

1 deprecation warning total

Finished in 0.00004 seconds
0 examples, 0 failures

Finished in 0.00004 seconds
0 examples, 0 failures
```

which is weird, as if it is ran twice!?

Version `2.14.1` however gives me:
```
No examples found.


Finished in 0.00004 seconds
0 examples, 0 failures
```

**Comment by stefanhendriks** [comment]
@myronmarston here is my `printenv`:

```
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.e1O3G46VUv/Listeners
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.ORyBrxzgx4/Render
COLORFGBG=12;8
ITERM_PROFILE=Default
XPC_FLAGS=0x0
PWD=/Users/shendriks/projects/fundynamic/rspec-invalid-option-1356
SHELL=/bin/zsh
SECURITYSESSIONID=186a5
LC_CTYPE=UTF-8
DESTINATION=/var/folders/08/d34b4nxn5pq844l68jr7_8300000gn/T/iTerm 2.0.0.20141103 Update
TERM_PROGRAM=iTerm.app
PATH=/Users/shendriks/.rvm/gems/ruby-2.0.0-p195@rspec-invalid-option-1356/bin:/Users/shendriks/.rvm/gems/ruby-2.0.0-p195@global/bin:/Users/shendriks/.rvm/rubies/ruby-2.0.0-p195/bin:/Users/shendriks/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/mysql/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin::/usr/local/heroku/bin::/usr/local/play-1.2.5.1/
DISPLAY=/private/tmp/com.apple.launchd.FIzOkdAL94/org.macosforge.xquartz:0
COMMAND_MODE=unix2003
TERM=xterm-256color
HOME=/Users/shendriks
TMPDIR=/var/folders/08/d34b4nxn5pq844l68jr7_8300000gn/T/
USER=shendriks
XPC_SERVICE_NAME=0
LOGNAME=shendriks
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
ITERM_SESSION_ID=w1t3p0
SHLVL=1
OLDPWD=/Users/shendriks/projects/fundynamic
rvm_prefix=/Users/shendriks
rvm_path=/Users/shendriks/.rvm
rvm_bin_path=/Users/shendriks/.rvm/bin
_system_type=Darwin
_system_name=OSX
_system_version=10.10
_system_arch=x86_64
rvm_version=1.26.11 (latest)
GEM_HOME=/Users/shendriks/.rvm/gems/ruby-2.0.0-p195@rspec-invalid-option-1356
GEM_PATH=/Users/shendriks/.rvm/gems/ruby-2.0.0-p195@rspec-invalid-option-1356:/Users/shendriks/.rvm/gems/ruby-2.0.0-p195@global
MY_RUBY_HOME=/Users/shendriks/.rvm/rubies/ruby-2.0.0-p195
IRBRC=/Users/shendriks/.rvm/rubies/ruby-2.0.0-p195/.irbrc
KEYTIMEOUT=1
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
WORKSPACE_PATH=/Users/shendriks/projects/
EDITOR=vim
MY_SENDMAIL_WORKS=true
RUBY_HEAP_SLOTS_INCREMENT=1000000
RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
RUBY_GC_MALLOC_LIMIT=100000000
RUBY_GC_HEAP_INIT_SLOTS=1000000
RUBY_HEAP_FREE_MIN=500000
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_ALL=en_US.UTF-8
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home
DART_HOME=/usr/local/opt/dart/libexec
MAVEN_OPTS=-Xms512m -Xmx2048m -XX:MaxPermSize=512m
JAVACMD=/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/bin/java
PS1=%F{250}%K{237} ~ %K{237}%F{244}⮁%F{250}%K{237} projects %K{237}%F{244}⮁%F{250}%K{237} fundynamic %K{237}%F{244}⮁%F{254}%K{237} rspec-invalid-option-1356 %K{161}%F{237}⮀%F{15}%K{161} master + %K{236}%F{161}⮀%F{15}%K{236} $  %f%k%F{236}⮀ %f%k
rvm_alias_expanded=
rvm_bin_flag=
rvm_docs_type=
rvm_gemstone_package_file=
rvm_gemstone_url=
rvm_niceness=
rvm_nightly_flag=
rvm_only_path_flag=
rvm_proxy=
rvm_quiet_flag=
rvm_ruby_bits=
rvm_ruby_file=
rvm_ruby_make=
rvm_ruby_make_install=
rvm_ruby_mode=
rvm_script_name=
rvm_sdk=
rvm_silent_flag=
rvm_use_flag=
rvm_wrapper_name=
RUBY_VERSION=ruby-2.0.0-p195
rvm_delete_flag=0
rvm_file_name=
rvm_ruby_alias=
rvm_sticky_flag=
rvm_system_flag=
rvm_user_flag=
rvm_ruby_string=ruby-2.0.0-p195
_=/usr/bin/printenv
```

**Comment by stefanhendriks** [comment]
Somewhere in `rspec-core` changelog I see: ``` Remove `--default_path` as an alias for `--default-path`. (Jon Rowe)``` starts to get me to something. Could it be `--default_path` is somewhere added under some circumstances?

**Comment by stefanhendriks** [comment]
Looking at the `option_parser` I see that the options passed to it are `[]` (which is correct, so there is no tool interfering and passing any invalid arguments). But at the end it still has as invalid option the `default_path` one. Digging further.

**Comment by stefanhendriks** [comment]
got a stacktrace:
```
/Users/shendriks/.rvm/gems/ruby-2.0.0-p195@rspec-invalid-option-1356/gems/rspec-core-3.2.3/lib/rspec/core/option_parser.rb:16:in `parse': invalid option: --default_path (OptionParser::InvalidOption)
	from /Users/shendriks/.rvm/gems/ruby-2.0.0-p195@rspec-invalid-option-1356/gems/rspec-core-3.2.3/lib/rspec/core/option_parser.rb:8:in `parse'
	from /Users/shendriks/.rvm/gems/ruby-2.0.0-p195@rspec-invalid-option-1356/gems/rspec-core-3.2.3/lib/rspec/core/configuration_options.rb:147:in `options_from'
	from /Users/shendriks/.rvm/gems/ruby-2.0.0-p195@rspec-invalid-option-1356/gems/rspec-core-3.2.3/lib/rspec/core/configuration_options.rb:143:in `global_options'
	from /Users/shendriks/.rvm/gems/ruby-2.0.0-p195@rspec-invalid-option-1356/gems/rspec-core-3.2.3/lib/rspec/core/configuration_options.rb:119:in `file_options'
	from /Users/shendriks/.rvm/gems/ruby-2.0.0-p195@rspec-invalid-option-1356/gems/rspec-core-3.2.3/lib/rspec/core/configuration_options.rb:44:in `organize_options'
	from /Users/shendriks/.rvm/gems/ruby-2.0.0-p195@rspec-invalid-option-1356/gems/rspec-core-3.2.3/lib/rspec/core/configuration_options.rb:14:in `initialize'
	from /Users/shendriks/.rvm/gems/ruby-2.0.0-p195@rspec-invalid-option-1356/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:59:in `new'
	from /Users/shendriks/.rvm/gems/ruby-2.0.0-p195@rspec-invalid-option-1356/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:59:in `run'
	from /Users/shendriks/.rvm/gems/ruby-2.0.0-p195@rspec-invalid-option-1356/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
	from /Users/shendriks/.rvm/gems/ruby-2.0.0-p195@rspec-invalid-option-1356/gems/rspec-core-3.2.3/exe/rspec:4:in `<top (required)>'
	from /Users/shendriks/.rvm/gems/ruby-2.0.0-p195@rspec-invalid-option-1356/bin/rspec:31:in `load'
	from /Users/shendriks/.rvm/gems/ruby-2.0.0-p195@rspec-invalid-option-1356/bin/rspec:31:in `<main>'
	from /Users/shendriks/.rvm/gems/ruby-2.0.0-p195@rspec-invalid-option-1356/bin/ruby_executable_hooks:15:in `eval'
	from /Users/shendriks/.rvm/gems/ruby-2.0.0-p195@rspec-invalid-option-1356/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by stefanhendriks** [comment]
***FOUND IT***

Ok, so I had a `.rspec` file in my home dir which had the invalid option.... I totally forgot I had this...

it would be kinda nice to have some hints where this could be perhaps?

**Comment by myronmarston** [comment]
> Ok, so I had a `.rspec` file in my home dir (`~/.rspec`) which had the invalid option.... I totally forgot I had this...

Good sleuthing, and thanks for reporting back about the problem.  It's definitely non-obvious.

> it would be kinda nice to have some hints where this could be perhaps?

Yep.  See rspec/rspec-core#1940 :).
