### ISSUE TITLE
rails generate migration fails with undefined method `start_with?'

### ISSUE THREAD

**Issue by dankohn** [rspec/rspec-rails#1412]
I'm getting this error:
```
$ rails generate migration some_name
/Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec-rails.rb:15:in `block (2 levels) in <class:Railtie>': undefined method `start_with?' for :test_unit:Symbol (NoMethodError)
	from /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec-rails.rb:15:in `reject!'
	from /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-rails-3.3.2/lib/rspec-rails.rb:15:in `block in <class:Railtie>'
	from /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/railtie.rb:228:in `call'
	from /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/railtie.rb:228:in `block in run_generators_blocks'
	from /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/railtie.rb:245:in `each'
	from /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/railtie.rb:245:in `each_registered_block'
	from /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/railtie.rb:228:in `run_generators_blocks'
	from /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/application.rb:462:in `block in run_generators_blocks'
	from /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/engine/railties.rb:13:in `each'
	from /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/engine/railties.rb:13:in `each'
	from /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/application.rb:462:in `run_generators_blocks'
	from /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/engine.rb:461:in `load_generators'
	from /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:129:in `generate_or_destroy'
	from /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

FYI, my `application.rb` includes:
```ruby
class Application < Rails::Application
    config.active_record.schema_format = :sql

    config.generators do |g|
      g.hidden_namespaces << :test_unit << :erb
      g.template_engine :slim
      g.helper false
      g.test_framework :rspec, view_specs: false
      g.integration_tool :rspec
      g.fixture_replacement :factory_girl
      g.factory_girl dir: 'spec/factories'
      g.javascript_engine false
      g.scaffold_controller 'responders_controller'
      g.stylesheets false
    end
```

FYI: @slavad

**Comment by cupakromer** [comment]
Thanks for reporting this! :heart: I see what is going on, we're assuming the `hidden_namespaces` are `String` objects; which the defaults are. We'll get this fixed :smile_cat: :+1:

As a work around could you change your setup to use:

```ruby
config.generators do |g|
  g.hidden_namespaces << 'test_unit' << 'erb'
  #...
end
```

**Comment by dankohn** [comment]
Thanks. Please see my proposed fix: https://github.com/spreemo/rspec-rails/commit/2ffdaacb71d131cf581aac3a0408bf15dfa0e3ae

**Comment by cupakromer** [comment]
@dankohn would you like to submit that as a PR?
