### ISSUE TITLE
Type Error while posting JSON but only in Rspec

### ISSUE THREAD

**Issue by KingsleyKelly** [rspec/rspec-rails#1421]
I'm making the following API call

```ruby
      json = %q{{
         "answers" : [
            {
               "response" : "TEST",
               "question" : {
                  "title" : "TEST"
               }
            },
            {
               "question" : {
                  "title" : "Tests"
               },
               "response" : [
                  "Test"
               ]
            }
         ]
      }}
      json = JSON.parse(json)
      webhook = post("/test", json)
```

And it throws the following error
````
     TypeError:
       expected Array (got String) for param `response'
     # ./spec/requests/api/v1/test_spec.rb:32:in `block (3 levels) in <top (required)>'
````
It fails on the webhook   = post("/test", json) line.
Where this gets a bit crazy is that this JSON parses fine, and I can make a post request against the endpoint with this data format and get the desired response (outside of rspec). I'm not sure if this is a problem in how I'm formatting my code or if it is in the post method. If I change the type of response to a String or change the name of the key than this will send fine.

**Comment by cupakromer** [comment]
Off the top of my head this sounds like a possible Rack issue. I was able to reproduce and this is the top of the stack:

```
Rack::Utils::ParameterTypeError:
  expected Array (got String) for param `response'
# .gem/ruby/2.2.0/gems/rack-1.6.2/lib/rack/utils.rb:149:in `normalize_params'
# .gem/ruby/2.2.0/gems/rack-1.6.2/lib/rack/utils.rb:156:in `normalize_params'
# .gem/ruby/2.2.0/gems/rack-1.6.2/lib/rack/utils.rb:122:in `block in parse_nested_query'
# .gem/ruby/2.2.0/gems/rack-1.6.2/lib/rack/utils.rb:119:in `each'
# .gem/ruby/2.2.0/gems/rack-1.6.2/lib/rack/utils.rb:119:in `parse_nested_query'
# .gem/ruby/2.2.0/gems/rack-1.6.2/lib/rack/request.rb:369:in `parse_query'
# .gem/ruby/2.2.0/gems/rack-1.6.2/lib/rack/request.rb:215:in `POST'
# .gem/ruby/2.2.0/gems/rack-1.6.2/lib/rack/methodoverride.rb:39:in `method_override_param'
# .gem/ruby/2.2.0/gems/rack-1.6.2/lib/rack/methodoverride.rb:27:in `method_override'
# .gem/ruby/2.2.0/gems/rack-1.6.2/lib/rack/methodoverride.rb:15:in `call'
# .gem/ruby/2.2.0/gems/rack-1.6.2/lib/rack/runtime.rb:18:in `call'
# .gem/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
# .gem/ruby/2.2.0/gems/rack-1.6.2/lib/rack/lock.rb:17:in `call'
# .gem/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/middleware/static.rb:113:in `call'
# .gem/ruby/2.2.0/gems/rack-1.6.2/lib/rack/sendfile.rb:113:in `call'
# .gem/ruby/2.2.0/gems/railties-4.2.2/lib/rails/engine.rb:518:in `call'
# .gem/ruby/2.2.0/gems/railties-4.2.2/lib/rails/application.rb:164:in `call'
# .gem/ruby/2.2.0/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
# .gem/ruby/2.2.0/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
# .gem/ruby/2.2.0/gems/rack-test-0.6.3/lib/rack/test.rb:124:in `request'
# .gem/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/testing/integration.rb:297:in `process'
# .gem/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/testing/integration.rb:38:in `post'
# .gem/ruby/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/testing/integration.rb:344:in `block (2 levels) in <module:Runner>'
# ./spec/requests/test_spec.rb
```

I'll dig into it a bit more as in this same project I have many working request specs.

**Comment by myronmarston** [comment]
I believe the problem is that you are passing a ruby hash (with nested arrays and hashes) as the 2nd argument to `post`.  HTTP (which rack-test simulates) does not understand ruby hashes and arrays.  It understands only text.  Whenever I've used rack-test and done a POST request to a JSON API endpoint, I've always passed a JSON string as the second argument rather than ruby objects parsed from JSON.

There might be a way to make it work by setting the `Content-Type` request header to `application/json` (that way, rack-test will know what encoding you intend) but without that I don't see anyway it could possibly work to pass ruby objects.

**Comment by JonRowe** [comment]
@KingsleyKelly you should just be able to post the raw string to the endpoint and let rails do the json decoding

**Comment by KingsleyKelly** [comment]
Hey guys thanks for the answers! Sorry for being slow to respond.
I got this working thanks to your help!
After submitting it as a string I get the following object

````
{"{\"answers\" : "=>{"{\"response\" : \"TEST\",\"question\" : {\"title\" : \"TEST\"}},{\"question\" : {\"title\" : \"Tests\"},\"response\" : "=>{"\"Test\""=>{"}"=>{"}"=>nil}}}}}
````

Where it's creating incorrect keys. This is why I switched to trying to parse the JSON before in the first place.
I checked in the env at this point and realised it wasn't being accepted as json by rails.
After specifying
```` 
{
  'HTTP_ACCEPT' => 'application/json',
  'CONTENT_TYPE' => 'application/json'
}
````

As the third argument it realised it wasn't a form and parsed it correctly.

Thanks again.

**Comment by cupakromer** [comment]
Just figured out what is happening. It has to do with the default request type being a "form" for the request. When Rack parses the form it attempt to merge nested hashes in an array. When the hash values are of different types it freaks out and cause the error you saw.

Here's a step-by-step expanding of the request and params adding more until it breaks:

```ruby
post(
  "/docs",
  {
    "answers" => []
  }
)
# params => {}

post(
  "/docs",
  {
    "answers" => [
      { "hash" => { "key_a" => "value_a"} },
    ]
  }
)
# params => {"answers"=>[{"hash"=>{"key_a"=>"value_a"}}]}

post(
  "/docs",
  {
    "answers" => [
      { "hash" => { "key_a" => "value_a" }, "array" => ["value_a"] },
    ]
  }
)
# params => {"answers"=>[{"hash"=>{"key_a"=>"value_a"}, "array"=>["value_a"]}]}

post(
  "/docs",
  {
    "answers" => [
      { "hash" => { "key_a" => "value_a" }, "array" => ["value_a"] },
      { "hash" => { "key_b" => "value_b" }, "array" => ["value_b"] },
    ]
  }
)
# params => {"answers"=>[{"hash"=>{"key_a"=>"value_a", "key_b"=>"value_b"},
#                         "array"=>["value_a", "value_b"]}]}

post(
  "/docs",
  {
    "answers" => [
      { "hash" => { "key_a" => "value_a" }, "array" => "value_a" },
      { "hash" => { "key_b" => "value_b" }, "array" => ["value_b"] },
    ]
  }
)
# Exception!
```

The strange thing is for the one that cause the exception, if you change the order of the submitted params it works:

```ruby
post(
  "/docs",
  {
    "answers" => [
      { "hash" => { "key_a" => "value_a" }, "array" => "value_a" },
      { "hash" => { "key_b" => "value_b" }, "array" => ["value_b"] },
    ]
  }
)
# params => {"answers"=>[{"hash"=>{"key_a"=>"value_a", "key_b"=>"value_b"},
#                         "array"=>["value_a"]},
#                        {"array"=>"value_b"}]}
```
