### ISSUE TITLE
url_for throws UrlGenerationError in view spec after upgrading to Rails 4.0

### ISSUE THREAD

**Issue by agis-** [rspec/rspec-rails#1451]
*This is cross-posted to https://github.com/rails/rails/issues/21398.*

Not sure if this is a Rails or an RSpec issue but here I go.

In the process of upgrading to Rails 4.1.12 from 3.2, I've encountered some test failures that I believe are related to https://github.com/rails/rails/commit/dc663dd52c99ab6e6c633b54d1a0e836f379bf9f. I'm using rspec-rails 3.2.1.

I have the following (stripped down) view:

```erb
# app/views/categories/show/_page_item.html.erb
<% url_for("controller"=>"categories", "action"=>"show", "category_id"=>"40", "category_name"=>"foo", "page"=>2) %>
```

and the corresponding spec:

```ruby
# spec/views/categories/show/_page_item.html.erb_spec.rb
require 'spec_helper'

describe 'categories/show/_page_item.html.erb' do
  it "does not explode" do
    render 'page_item.html.erb'
  end
end
```

and finally the relevant route:

```
category GET          /c/:category_id/:category_name(/m/:manufacturer_id/:manufacturer)(/s/:shop_id/:shop)(/f/:filter_id/:filter).html(.:format) categories#show {:category_id=>/\d+/, :category_name=>/[^\/]+/, :manufacturer_id=>/[0-9_]+/, :manufacturer=>/[^\/]+/, :shop_id=>/[0-9_]+/, :shop=>/[^\/]+/, :filter_id=>/[0-9_]+/, :filter=>/[^\/]+/}
```

This tests fails after upgrading to Rails 4.0 like so:

```shell
ActionView::Template::Error:
  No route matches {:action=>"show", :category_id=>"40", :category_name=>"kinhta-thlefwna", :controller=>"categories/categories", :page=>2}
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_dispatch/journey/formatter.rb:39:in `generate'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:597:in `generate'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:627:in `generate'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:663:in `url_for'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_dispatch/routing/url_for.rb:155:in `url_for'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/routing_url_for.rb:83:in `url_for'
# ./app/views/categories/show/_page_item.html.erb:2:in `_app_views_categories_show__page_item_html_erb__151325937655746978_70288869015880'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/template.rb:143:in `block in render'
# /Users/agis/.gem/ruby/2.1.5/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `block in instrument'
# /Users/agis/.gem/ruby/2.1.5/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
# /Users/agis/.gem/ruby/2.1.5/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `instrument'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/template.rb:141:in `render'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/renderer/template_renderer.rb:49:in `block (2 levels) in render_template'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
# /Users/agis/.gem/ruby/2.1.5/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `block in instrument'
# /Users/agis/.gem/ruby/2.1.5/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
# /Users/agis/.gem/ruby/2.1.5/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `instrument'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/renderer/template_renderer.rb:48:in `block in render_template'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/renderer/template_renderer.rb:56:in `render_with_layout'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/renderer/template_renderer.rb:47:in `render_template'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/renderer/template_renderer.rb:17:in `render'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/renderer/renderer.rb:42:in `render_template'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/renderer/renderer.rb:23:in `render'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/helpers/rendering_helper.rb:24:in `render'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/test_case.rb:195:in `render'
# /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/test_case.rb:115:in `render'
# ./spec/views/categories/show/_page_item.html.erb_spec.rb:14:in `block (2 levels) in <top (required)>'
```

The same test passes in Rails 3.2. Also, in development the view works normally and the url helpers work in both development & test when I call them from the console, so I suspect it's something with ActionView's `#url_for`.

After some digging, I've seen that when `ActionDispatch::Routing::UrlFor#url_for` is eventually called by ActionView at [this point](https://github.com/rails/rails/blob/v4.0.12/actionpack/lib/action_view/routing_url_for.rb#L82), `ActionView::RoutingUrlFor#url_options` seems to return the wrong result (not sure though)

In fact this is returned by:

```ruby
From: /Users/agis/.gem/ruby/2.1.5/gems/actionpack-4.0.13/lib/action_view/routing_url_for.rb @ line 93 ActionView::RoutingUrlFor#url_options:

    91: def url_options #:nodoc:
    92:   return super unless controller.respond_to?(:url_options)
 => 93:   controller.url_options
    94: end

[18] pry(#<#<Class:0x007ffaeee411a0>>)> controller.url_options
=> {:host=>"test.host",
 :port=>nil,
 :protocol=>"http://",
 :_recall=>{:controller=>"categories/show"}}

[19] pry(#<#<Class:0x007ffaeee411a0>>)>controller.lookup_context.prefixes
=> ["", "categories/show"]
```

So it seems that either RSpec does not setup the controller object correctly or it's something in Rails.

Note: The issue also happens in 4.1.12.

Thanks!

**Comment by cupakromer** [comment]
What is your rspec version?

**Comment by agis-** [comment]
@cupakromer 3.2.0.

**Comment by cupakromer** [comment]
From the code sample it doesn't look like the spec is tagged with a metadata `:type` (i.e. `type: :view`). Have you enabled [`infer_spec_type_from_file_location!`](https://www.relishapp.com/rspec/rspec-rails/v/3-0/docs/upgrade#file-type-inference-disabled)?

**Comment by agis-** [comment]
Yes it's enabled in my `spec_helper.rb`.

**Comment by tilo** [comment]
any updates? I'm running into the same issue with Controller Specs .. none of the routes seem to match, although `rake routes` shows them

rspec-rails 3.3.3
rspec 3.3.0
Rails 4.2.4
Ruby 2.2.2

**Comment by samphippen** [comment]
@agis- can you send us a github repo with a small rails app to demonstrate this issue that we can debug against? Specifically, we'd like to see two things:

1. A commit which is just initialising an empty rails app
2. A second commit which includes all of the changes you made to demonstrate the issue.

If you could keep the example as small as possible, that will help us debug this.

**Comment by jasnow** [comment]
@agis- Is your repo public? If so, I will be glad to help.

**Comment by jasnow** [comment]
@aegis - What version of rspec did not use with Rails 3.2?

**Comment by jasnow** [comment]
In: http://rspec.info/blog/2014/05/notable-changes-in-rspec-3, I found this:
```
To explicitly tag specs without using automatic inference, set the type metadata:

RSpec.describe ThingsController, type: :controller do
  # Equivalent to being in spec/controllers
end
```

**Comment by jasnow** [comment]
@aegis - What's your status on this issue?

**Comment by samphippen** [comment]
I'm going to close this issue. @agis- if you can provide us with a reproduction case we'll happily re-open and take a look.
