### ISSUE TITLE
Namespaced Controller Specs blow up

### ISSUE THREAD

**Issue by tilo** [rspec/rspec-rails#1453]
Namespaced Controller Specs blow up  .. none of the routes seem to match, although rake routes shows them
rspec-rails 3.3.3
rspec 3.3.0
Rails 4.2.4
Ruby 2.2.2
See:[https://github.com/tilo/deleteme](https://github.com/tilo/deleteme)

```
describe Api::V1::PagesController, :type => :controller do
  describe 'GET #status' do
    it 'returns successfully' do
      get :status
      expect(response).to  be_success
    end
  end
end
```

```

  1) Api::V1::PagesController GET #status returns successfully
     Failure/Error: get :status
     ActionController::UrlGenerationError:
       No route matches {:action=>"status", :controller=>"api/v1/pages"}
     # /Users/tilo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/journey/formatter.rb:46:in `generate'
     # /Users/tilo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:729:in `generate'
     # /Users/tilo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:760:in `generate'
     # /Users/tilo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:755:in `generate_extras'
     # /Users/tilo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:750:in `extra_keys'
     # /Users/tilo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_controller/test_case.rb:208:in `assign_parameters'
     # /Users/tilo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_controller/test_case.rb:624:in `process'
     # /Users/tilo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_controller/test_case.rb:65:in `process'
     # /Users/tilo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_controller/test_case.rb:512:in `get'
     # ./spec/controllers/api/v1/pages_controller_spec.rb:6:in `block (3 levels) in <top (required)>'
```

```
rake routes
      Prefix Verb URI Pattern                    Controller#Action
pages_status GET  /pages/status(.:format)        pages#status
  api_status GET  /api/:version/status(.:format) api/v1/pages#status {:format=>"json", :version=>/(1)/}
```

**Comment by JonRowe** [comment]
It looks like your missing the format so the route matches correctly, try adding `format: :json` as a second parameter to your `get`

**Comment by tilo** [comment]
that did not change it - problem persists.

```
1) Api::V1::PagesController GET #status returns OK
     Failure/Error: get :status, :format => :json
     ActionController::UrlGenerationError:
       No route matches {:action=>"status", :controller=>"api/v1/pages", :format=>:json}
     # /Users/tilo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/journey/formatter.rb:46:in `generate'
     # /Users/tilo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:729:in `generate'
     # /Users/tilo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:760:in `generate'
     # /Users/tilo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:755:in `generate_extras'
     # /Users/tilo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:750:in `extra_keys'
     # /Users/tilo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_controller/test_case.rb:208:in `assign_parameters'
     # /Users/tilo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_controller/test_case.rb:624:in `process'
     # /Users/tilo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_controller/test_case.rb:65:in `process'
     # /Users/tilo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_controller/test_case.rb:512:in `get'
     # ./spec/controllers/api/v1/pages_controller_spec.rb:6:in `block (3 levels) in <top (required)>'
```

**Comment by tilo** [comment]
looks like the default values  {:format=>"json", :version=>/(1)/}  need to be set explicitly in the spec file

**Comment by JonRowe** [comment]
Ah you'll also need the `:version` specified too of course, oops :)
