### ISSUE TITLE
Anonymous controllers don't have access to "let" variables

### ISSUE THREAD

**Issue by Bartuz** [rspec/rspec-rails#1506]
I'm testing some `before_action`s on anonymous controllers
```
RSpec.describe MyBaseController, type: :controller do
  let(:text) { 'Grief is the price we pay for love. ~ Queen Elizabeth II' }
  let(:secret_message) { 'You miss 100% of the shots you don’t take. ~ Wayne Gretzky' }

  controller do
    SECRET_MESSAGE = secret_message

    def index
      render text: text
    end
  end

  it 'does things' do
    get :index
  end
end
```

and this fails at two stages.  
1. On RSpec load stage (before any specs are run)
2.  (After `SECRET_MESSAGE = secret_message` is removed from controller) While specs are running

I wonder if it's a bug or intended thing. Here are errors messages.

1. On load stage

```
/Users/filip/dev/mybasecontroller_spec.rb:10:in `block (2 levels) in <top (required)>': undefined local variable or method `secret_message' for #<Class:0x007fa1381b2a20> (NameError)
	from /Users/filip/.rvm/gems/ruby-2.2.1/gems/rspec-rails-3.4.0/lib/rspec/rails/example/controller_example_group.rb:77:in `class_exec'
	from /Users/filip/.rvm/gems/ruby-2.2.1/gems/rspec-rails-3.4.0/lib/rspec/rails/example/controller_example_group.rb:77:in `controller'
	from /Users/filip/dev/onepagecrm/web-application/spec/controllers/webhooks/base_controller_spec.rb:9:in `block in <top (required)>'
	from /Users/filip/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:385:in `module_exec'
	from /Users/filip/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:385:in `subclass'
	from /Users/filip/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:255:in `block in define_example_group_method'
	from /Users/filip/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.1/lib/rspec/core/dsl.rb:43:in `block in expose_example_group_alias'
	from /MyBaseController_spec.rb:3:in `<top (required)>'
	from /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /Users/filip/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /Users/filip/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `each'
	from /Users/filip/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /Users/filip/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:102:in `setup'
	from /Users/filip/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:88:in `run'
	from /Users/filip/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
	from /Users/filip/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
	from /Users/filip/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.1/exe/rspec:4:in `<top (required)>'
	from bin/rspec:23:in `load'
```
2. On run stage:
```
     NameError:
       undefined local variable or method `text' for #<#<Class:0x007f83a2706bb0>:0x007f83a1f7a338>
     # ./spec/controllers/my_base__controller_spec.rb:14:in `index'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.5/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.5/lib/abstract_controller/base.rb:198:in `process_action'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.5/lib/action_controller/metal/rendering.rb:10:in `process_action'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.5/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:313:in `call'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
     # ./app/controllers/application_controller.rb:23:in `request_context'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:432:in `block in make_lambda'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:312:in `call'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:312:in `block in halting'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:497:in `call'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:497:in `block in around'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.5/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.5/lib/action_controller/metal/rescue.rb:29:in `process_action'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.5/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `block in instrument'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `instrument'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.5/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.5/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.5/lib/abstract_controller/base.rb:137:in `process'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/actionview-4.2.5/lib/action_view/rendering.rb:30:in `process'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.5/lib/action_controller/test_case.rb:639:in `process'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.5/lib/action_controller/test_case.rb:67:in `process'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/gon-6.0.1/lib/gon/spec_helpers.rb:15:in `process'
     # /Users/filip/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.5/lib/action_controller/test_case.rb:520:in `post'
     # ./spec/controllers/my_base_controller_spec.rb:19:in `block (3 levels) in <top (required)>'
     # ./spec/controllers/my_base_controller_spec.rb:46:in `block (4 levels) in <top (required)>'
```

**Comment by JonRowe** [comment]
An anonymous controller is executed in the content of a controller and not in the context of a test, so this is a side effect of how Ruby's scoping works. If you want to replicate this behaviour something like this should work:

```ruby
RSpec.describe MyBaseController, type: :controller do
  text = 'Grief is the price we pay for love. ~ Queen Elizabeth II'.freeze
  secret_message =  'You miss 100% of the shots you don’t take. ~ Wayne Gretzky'.freeze

  controller do
    SECRET_MESSAGE = secret_message

    def index
      render text: text
    end
  end

  it 'does things' do
    get :index
  end
end
```

Which I believe will work because local variables are accessible in the block when defined like that. Local variables aren't considered best practise when used with objects but for simple primitives like a string there should be no down side. The `.freeze` is to prevent mutation between tests.
