### ISSUE TITLE
Issue with rspec:install

### ISSUE THREAD

**Issue by dsarhadian** [rspec/rspec-rails#1509]
Hi everyone, 

I'm trying to use rspec in my new app, but when I run the rails g rspec:install command, I get the following error:

```
/home/dro/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler/setup (LoadError)
	from /home/dro/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/dro/Projects/best-deliveries-api/vendor/ruby/2.2.0/gems/spring-1.6.1/lib/spring/commands.rb:33:in `<module:Spring>'
	from /home/dro/Projects/best-deliveries-api/vendor/ruby/2.2.0/gems/spring-1.6.1/lib/spring/commands.rb:4:in `<top (required)>'
	from /home/dro/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/dro/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/dro/Projects/best-deliveries-api/vendor/ruby/2.2.0/gems/spring-1.6.1/lib/spring/application.rb:77:in `preload'
	from /home/dro/Projects/best-deliveries-api/vendor/ruby/2.2.0/gems/spring-1.6.1/lib/spring/application.rb:143:in `serve'
	from /home/dro/Projects/best-deliveries-api/vendor/ruby/2.2.0/gems/spring-1.6.1/lib/spring/application.rb:131:in `block in run'
	from /home/dro/Projects/best-deliveries-api/vendor/ruby/2.2.0/gems/spring-1.6.1/lib/spring/application.rb:125:in `loop'
	from /home/dro/Projects/best-deliveries-api/vendor/ruby/2.2.0/gems/spring-1.6.1/lib/spring/application.rb:125:in `run'
	from /home/dro/Projects/best-deliveries-api/vendor/ruby/2.2.0/gems/spring-1.6.1/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /home/dro/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/dro/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

All of my gems are up to date, I'm running Rails version 4.2.5 and Ruby version 2.2.3.

Can anyone help?

**Comment by jasnow** [comment]
This is probably a spring gem issue. Try locking it down to spring '1.5.0' to see root cause.

**Comment by dsarhadian** [comment]
Hi @jasnow, I added that to my gem file, ran bundle update, and then the rspec:install command and still getting the same results.

**Comment by jasnow** [comment]
Is your repo public? If so, add URL as a comment.

**Comment by dsarhadian** [comment]
Hi @jasnow,

The repo isn't public but it is a brand new rails app. There have been no changes to any files except the Gemfile to add the rspec_rails gem.

**Comment by jasnow** [comment]
Tried to reproduce:
```
 1. Run 'rvm install 2.2.4'
 2. Run 'gem install rails -v 5.0.0.beta1'
 3. Run 'rails new myappdec22 --edge'
 4. cd myappdec22
 5. Removed comments from Gemfile.
 6. Added "gem 'rspec-rails" to Gemfile.
 7. Run 'bundle'
 8. Set up .rvmrc file.
 9. Run 'cd .. ; cd myappdec22'
 10. Set up Git and repo on Github. See it at jasnow/myappdec22 repo.
 11. Run 'rake' (green)
 12. Run 'rails generate rspec:install'
 13. Run 'rake' (green)
```
What did I miss?

**Comment by jasnow** [comment]
@dsarhadian - Can you fork my **myappdec22** app, reproduce the above issue, and send me a pull request so I work it. I can't reproduce it locally. Thanks.

**Comment by dsarhadian** [comment]
@jasnow - It looked like it was a spring issue... I tinkered with it a bit more and got it to work properly. Thanks for your help!

**Comment by jasnow** [comment]
You are welcome.
