### ISSUE TITLE
Rails 5 - undefined method `polymorphic_path' when running tests

### ISSUE THREAD

**Issue by Jelkster** [rspec/rspec-rails#1538]
When running tests on a Rails 5 build, they fail as follows:

```
Failures:

  1) donations/edit renders the edit donation form
     Failure/Error: <%= form_for(donation) do |f| %>
     
     ActionView::Template::Error:
       undefined method `polymorphic_path' for #<#<Class:0x007f84dd193a20>:0x007f84dd192670>
     # ./app/views/donations/_form.html.erb:1:in `_app_views_donations__form_html_erb___3852279999991182218_70104310745880'
     # ./app/views/donations/edit.html.erb:3:in `_app_views_donations_edit_html_erb___452257336685137231_70104310796040'
     # ./spec/views/donations/edit.html.erb_spec.rb:23:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `polymorphic_path' for #<#<Class:0x007f84dd193a20>:0x007f84dd192670>
     #   ./app/views/donations/_form.html.erb:1:in `_app_views_donations__form_html_erb___3852279999991182218_70104310745880'

  2) donations/index renders a list of donations
     Failure/Error: <td><%= link_to 'Show', donation %></td>
     
     ActionView::Template::Error:
       arguments passed to url_for can't be handled. Please require routes or provide your own implementation
     # ./app/views/donations/index.html.erb:41:in `block in _app_views_donations_index_html_erb___3318947387408484384_70104283061420'
     # ./app/views/donations/index.html.erb:26:in `each'
     # ./app/views/donations/index.html.erb:26:in `_app_views_donations_index_html_erb___3318947387408484384_70104283061420'
     # ./spec/views/donations/index.html.erb_spec.rb:40:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # ArgumentError:
     #   arguments passed to url_for can't be handled. Please require routes or provide your own implementation
     #   ./app/views/donations/index.html.erb:41:in `block in _app_views_donations_index_html_erb___3318947387408484384_70104283061420'

  3) donations/new renders new donation form
     Failure/Error: <%= form_for(donation) do |f| %>
     
     ActionView::Template::Error:
       undefined method `polymorphic_path' for #<#<Class:0x007f84dd193a20>:0x007f84d967dc88>
     # ./app/views/donations/_form.html.erb:1:in `_app_views_donations__form_html_erb___3852279999991182218_70104310745880'
     # ./app/views/donations/new.html.erb:3:in `_app_views_donations_new_html_erb___1181596900630081682_70104279676460'
     # ./spec/views/donations/new.html.erb_spec.rb:23:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `polymorphic_path' for #<#<Class:0x007f84dd193a20>:0x007f84d967dc88>
     #   ./app/views/donations/_form.html.erb:1:in `_app_views_donations__form_html_erb___3852279999991182218_70104310745880'

  4) donations/show renders attributes in <p>
     Failure/Error: <%= link_to 'Edit', edit_donation_path(@donation) %> |
     
     ActionView::Template::Error:
       undefined method `edit_donation_path' for #<#<Class:0x007f84dd193a20>:0x007f84dabf2528>
     # ./app/views/donations/show.html.erb:68:in `_app_views_donations_show_html_erb___2477893337197169895_70104290891780'
     # ./spec/views/donations/show.html.erb_spec.rb:23:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `edit_donation_path' for #<#<Class:0x007f84dd193a20>:0x007f84dabf2528>
     #   ./app/views/donations/show.html.erb:68:in `_app_views_donations_show_html_erb___2477893337197169895_70104290891780'

Finished in 0.58493 seconds (files took 1.85 seconds to load)
30 examples, 4 failures, 16 pending

Failed examples:

rspec ./spec/views/donations/edit.html.erb_spec.rb:22 # donations/edit renders the edit donation form
rspec ./spec/views/donations/index.html.erb_spec.rb:39 # donations/index renders a list of donations
rspec ./spec/views/donations/new.html.erb_spec.rb:22 # donations/new renders new donation form
rspec ./spec/views/donations/show.html.erb_spec.rb:22 # donations/show renders attributes in <p>
```

The same can also be observed on Travis:
https://travis-ci.org/Jelkster/repay_music/builds/105021996

I have all the rspec gems pointing to master.

**Comment by jasnow** [comment]
Check out this: https://github.com/rails/rails/issues/22794

**Comment by JonRowe** [comment]
As per @jasnow's feedback are you using Rails 5 beta 1 or Rails master?

**Comment by Jelkster** [comment]
beta 1.  running `rails server` actually crashes on me when i try master, so i expect to be submitting an issue related to that soon as well.

**Comment by jasnow** [comment]
Got "rails server" working, see my fork for my changes - used sqlite3 to simplify.

**Comment by Jelkster** [comment]
Thanks for taking a look @jasnow.  Regarding `rails s` when I ran it, I got the following message:
```
bundler/gems/rails-c48790e4f6d3/activesupport/lib/active_support/dependencies.rb:302:
in `require': cannot load such file -- action_cable/process/logging (LoadError)
```
And it looks like you [commented it out](https://github.com/jasnow/repay_music/blob/666b4302acdc4e23569fae4123e9e1990f2dec3a/config.ru#L7) which would explain why it's working now.

**Comment by samphippen** [comment]
@Jelkster are you using the [rails controller testing](https://github.com/rails/rails-controller-testing) gem?

If not, could you do the following:

0) start a new git repo
1) rails new an app at rails 5 and commit **just the rails new**
2) make all the changes necessary to expose the bug?
3) push the repo up to GitHub and link it here?

Having a clean repro is going to make this a lot easier to work through.

**Comment by Jelkster** [comment]
@samphippen so of course a newly created app passed with flying colors.  I *was* using the rails controller testing gem **however**, I did not have it pointing to master.  Once I did that, the errors went away.  YAY!!!
