### ISSUE TITLE
undefined method `>' for nil:NilClass

### ISSUE THREAD

**Issue by slava-nikulin** [rspec/rspec-rails#1604]
Can you help me to solve this issue?
```Ruby
Failure/Error: if(@gc_every_n_examples > 0)
Trace:
/.rvm/gems/ruby-1.9.3-p551@rails3112/bundler/gems/rspec-gc-control-bc67f4b6fbb6/lib/rspec-gc-control/configuration.rb:24:in `gc_if_needed'
/.rvm/gems/ruby-1.9.3-p551@rails3112/bundler/gems/rspec-gc-control-bc67f4b6fbb6/lib/rspec-gc-control/example.rb:16:in `run_after_example'
```

**Comment by JonRowe** [comment]
You have an extension called `rspec-gc-control` that's raise an error, I suggest you contact the authors of that library.

**Comment by slava-nikulin** [comment]
Oh, thx!
