### ISSUE TITLE
expect(response).to redirect_to(document_path(assigns(:document))) fails with missing [:id]

### ISSUE THREAD

**Issue by mbmasuda** [rspec/rspec-rails#1618]
Hi,

I have a couple of similar controller tests.  One is passing and the other is not, and I can't figure out what the difference is or where I've gone wrong.  I am using RSpec-Rails 3.4 and Rails 4.2.6.

The passing test:

```
  describe "POST #create as devcomm" do
    it "returns http success" do
      devcomm_user
      expect { post :create, project: {parent_id: nil, name: "Test", is_secret: false, disclosed_user_ids: []} }.to change(Project, :count).by(1)
      expect(response).to redirect_to(project_path(assigns(:project)))
    end
  end
```

The passing test controller:

```
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project successfully created.'
    else
      render "new"
    end
  end
```

The failing test:

```
  describe "POST #create" do
    it "as devcomm returns http success" do
      devcomm_user
      expect { post :create, document: {project_id: projects(:nonsecretproject1), name: "Test Document", is_secret: false, owner_ids: [users(:devcomm1)], reviewer_ids: [users(:nondevcomm1)]} }.to change(Document, :count).by(1)
      expect(response).to redirect_to(document_path(assigns(:document)))  ### fails here
    end
  end
```

The failing test controller:

```
  def create
    @doc = Document.new(document_params)

    if @doc.save
      redirect_to @doc, notice: 'Document successfully created.'
    else
      render "new"
    end
  end
```

The error:

```
  2) DocumentsController POST #create as devcomm returns http success
     Failure/Error: expect(response).to redirect_to(document_path(assigns(:document)))
     
     ActionController::UrlGenerationError:
       No route matches {:action=>"show", :controller=>"documents", :id=>nil} missing required keys: [:id]
     # ./spec/controllers/documents_controller_spec.rb:38:in `block (3 levels) in <top (required)>'
```

My routes:

```
                                 Prefix Verb   URI Pattern                                                                                  Controller#Action
                                   root GET    /                                                                                            index#dashboard
                  create_user_from_ajax POST   /create_user_from_ajax(.:format)                                                             users#create_user_from_ajax
        populate_document_reviewer_list GET    /populate_document_reviewer_list(.:format)                                                   documents#populate_document_reviewer_list
                                  users GET    /users(.:format)                                                                             users#index
                                        POST   /users(.:format)                                                                             users#create
                               new_user GET    /users/new(.:format)                                                                         users#new
                              edit_user GET    /users/:id/edit(.:format)                                                                    users#edit
                                   user GET    /users/:id(.:format)                                                                         users#show
                                        PATCH  /users/:id(.:format)                                                                         users#update
                                        PUT    /users/:id(.:format)                                                                         users#update
                                        DELETE /users/:id(.:format)                                                                         users#destroy
                               projects GET    /projects(.:format)                                                                          projects#index
                                        POST   /projects(.:format)                                                                          projects#create
                            new_project GET    /projects/new(.:format)                                                                      projects#new
                           edit_project GET    /projects/:id/edit(.:format)                                                                 projects#edit
                                project GET    /projects/:id(.:format)                                                                      projects#show
                                        PATCH  /projects/:id(.:format)                                                                      projects#update
                                        PUT    /projects/:id(.:format)                                                                      projects#update
                                        DELETE /projects/:id(.:format)                                                                      projects#destroy
    document_document_revision_comments GET    /documents/:document_id/document_revisions/:document_revision_id/comments(.:format)          comments#index
                                        POST   /documents/:document_id/document_revisions/:document_revision_id/comments(.:format)          comments#create
 new_document_document_revision_comment GET    /documents/:document_id/document_revisions/:document_revision_id/comments/new(.:format)      comments#new
edit_document_document_revision_comment GET    /documents/:document_id/document_revisions/:document_revision_id/comments/:id/edit(.:format) comments#edit
     document_document_revision_comment GET    /documents/:document_id/document_revisions/:document_revision_id/comments/:id(.:format)      comments#show
                                        PATCH  /documents/:document_id/document_revisions/:document_revision_id/comments/:id(.:format)      comments#update
                                        PUT    /documents/:document_id/document_revisions/:document_revision_id/comments/:id(.:format)      comments#update
                                        DELETE /documents/:document_id/document_revisions/:document_revision_id/comments/:id(.:format)      comments#destroy
            document_document_revisions GET    /documents/:document_id/document_revisions(.:format)                                         document_revisions#index
                                        POST   /documents/:document_id/document_revisions(.:format)                                         document_revisions#create
         new_document_document_revision GET    /documents/:document_id/document_revisions/new(.:format)                                     document_revisions#new
        edit_document_document_revision GET    /documents/:document_id/document_revisions/:id/edit(.:format)                                document_revisions#edit
             document_document_revision GET    /documents/:document_id/document_revisions/:id(.:format)                                     document_revisions#show
                                        PATCH  /documents/:document_id/document_revisions/:id(.:format)                                     document_revisions#update
                                        PUT    /documents/:document_id/document_revisions/:id(.:format)                                     document_revisions#update
                                        DELETE /documents/:document_id/document_revisions/:id(.:format)                                     document_revisions#destroy
                              documents GET    /documents(.:format)                                                                         documents#index
                                        POST   /documents(.:format)                                                                         documents#create
                           new_document GET    /documents/new(.:format)                                                                     documents#new
                          edit_document GET    /documents/:id/edit(.:format)                                                                documents#edit
                               document GET    /documents/:id(.:format)                                                                     documents#show
                                        PATCH  /documents/:id(.:format)                                                                     documents#update
                                        PUT    /documents/:id(.:format)                                                                     documents#update
                                        DELETE /documents/:id(.:format)                                                                     documents#destroy
```

According to https://www.relishapp.com/rspec/rspec-rails/v/3-4/docs/matchers/redirect-to-matcher I believe my failing test is written correctly.  However, when I change the failing line to `expect(response).to redirect_to(assigns(:document))` I get a different error message:

```
  3) DocumentsController POST #create as devcomm returns http success
     Failure/Error: expect(response).to redirect_to(assigns(:document))
     
       Expected response to be a redirect to <http://test.host/documents> but was a redirect to <http://test.host/documents/319073037>.
       Expected "http://test.host/documents" to be === "http://test.host/documents/319073037".
     # ./spec/controllers/documents_controller_spec.rb:38:in `block (3 levels) in <top (required)>'
```

**Comment by JonRowe** [comment]
`assigns(:document)` returns `@document` from the controller but your using `@doc` so `@document` is nil and has no id, so no route can match it.
