### ISSUE TITLE
DELETE Request spec wants number as first argument instead of url?

### ISSUE THREAD

**Issue by hmistry** [rspec/rspec-rails#1625]
Hi,

I'm performing the following API request spec test:
`delete "/api/notifications/unsubscribe", params: { device_token: device.device_token }, headers: headers(token: token)`

and I get the following error:
`*** "Delete" argument ""/api/notifications/unsubscribe"," needs to be a number`

I've checked the params/headers are correct, route does exist, and verified the route working using `curl`. Has the argument params changed for `delete` request spec testing?

Using Rails 5.0.0.rc1.

**Comment by JonRowe** [comment]
This method is implemented by Rails, have you checked their documentation?

**Comment by hmistry** [comment]
Thanks. I've looked at the docs and it says `delete(path, *args)`. I'll follow this up with the Rails team.

**Comment by hmistry** [comment]
@JonRowe Is there any other configuration I need for Rspec to work correctly with this Rails template - https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_master.rb?

Here is what I have but it's not working with Rspec. I'm thinking its probably a missing configuration thing because similar tests worked with Minitest and I'm just replacing Minitest in the above template with the Rspec version. (The goal is isolate the cause of the original posting above.)

```
require 'rspec/rails'
require 'rspec/autorun'

RSpec.describe "home page", :type => :request do
  it "subscribe_returns_success" do
    post '/subscribe', params: { device_token: "funny_token" }, headers: { "CONTENT_TYPE" => "application/json", "TOKEN" => "header_token" }
    expect(response.status).to eq(200)
  end

  it "unsubscribe_returns_success" do
    delete '/unsubscribe', params: { device_token: "funny_token" }, headers: { "CONTENT_TYPE" => "application/json", "TOKEN" => "header_token" }
    expect(response.status).to eq(200)
  end
end
```

**Comment by JonRowe** [comment]
Can you do `method(:delete).source_location` within your spec for me?

**Comment by hmistry** [comment]
In the isolated test scrip above, both `post` and `delete` fail.
 
Source location is:
`.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.rc1/lib/action_dispatch/testing/integration.rb", 490`

The failure is:
```
I, [2016-05-24T07:58:22.815225 #10768]  INFO -- : Started POST "/api/v0/subscribe" for 127.0.0.1 at 2016-05-24 07:58:22 -0700
D, [2016-05-24T07:58:22.816831 #10768] DEBUG -- : Error occurred while parsing request parameters.
Contents:

device_token=funny_token
F, [2016-05-24T07:58:22.819234 #10768] FATAL -- :   
F, [2016-05-24T07:58:22.819276 #10768] FATAL -- : ActionDispatch::ParamsParser::ParseError (822: unexpected token at 'device_token=funny_token'):
F, [2016-05-24T07:58:22.819294 #10768] FATAL -- :   
F, [2016-05-24T07:58:22.819306 #10768] FATAL -- : testcase.rb:84:in `block (2 levels) in <main>'
FI, [2016-05-24T07:58:22.821622 #10768]  INFO -- : Started DELETE "/api/v0/unsubscribe" for 127.0.0.1 at 2016-05-24 07:58:22 -0700
D, [2016-05-24T07:58:22.821974 #10768] DEBUG -- : Error occurred while parsing request parameters.

```

**Comment by JonRowe** [comment]
If you run your specs with `--backtrace` does it highlight where in rails it's going wrong?

**Comment by hmistry** [comment]
how would i run specs with backtrace when its embedded in the rails bug report template file?

**Comment by JonRowe** [comment]
No your specs

**Comment by hmistry** [comment]
I ran the `backtrace` on the original project. It fails in Rspec-expectations:

```
4) Notifications API DELETE /notifications/unsubscribe has status code 204
     Failure/Error: expect(response.status).to be(204)
       
       expected #<Fixnum:409> => 204
            got #<Fixnum:801> => 400
       
       Compared using equal?, which compares object identity,
       but expected and actual are not the same object. Use
       `expect(actual).to eq(expected)` if you don't care about
       object identity in this example.
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-expectations-3.1.2/lib/rspec/expectations/fail_with.rb:30:in `fail_with'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-expectations-3.1.2/lib/rspec/expectations/handler.rb:35:in `handle_failure'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-expectations-3.1.2/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-expectations-3.1.2/lib/rspec/expectations/expectation_target.rb:54:in `to'
     # ./spec/requests/api/v0/notifications_spec.rb:85:in `block (3 levels) in <top (required)>'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:152:in `instance_exec'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:152:in `block in run'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:222:in `call'
     # /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/rspec-rails-3.1.0/lib/rspec/rails/adapters.rb:72:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:322:in `instance_exec'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:322:in `instance_exec'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:380:in `execute_with'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:446:in `block (2 levels) in run'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:222:in `call'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:447:in `run'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:500:in `run'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:331:in `with_around_example_hooks'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:149:in `run'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:490:in `block in run_examples'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:486:in `map'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:486:in `run_examples'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:453:in `run'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:454:in `block in run'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:454:in `map'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:454:in `run'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:111:in `block (2 levels) in run_specs'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:111:in `map'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:111:in `block in run_specs'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/reporter.rb:53:in `report'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:107:in `run_specs'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:85:in `run'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
     # /Users/hm/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
     # /Users/hm/.rvm/gems/ruby-2.3.0@global/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
     # /Users/hm/.rvm/gems/ruby-2.3.0@global/bin/rspec:23:in `load'
     # /Users/hm/.rvm/gems/ruby-2.3.0@global/bin/rspec:23:in `<main>'
     # /Users/hm/.rvm/gems/ruby-2.3.0@loop_server/bin/ruby_executable_hooks:15:in `eval'
     # /Users/hm/.rvm/gems/ruby-2.3.0@loop_server/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by JonRowe** [comment]
Thats not the same error you opened with and in fact is not an error but simply a failing test...

**Comment by hmistry** [comment]
Yes its failing the test but when pause on the test, and probe why the request is failing, its because its looking for a number in the `delete` method arguments instead of a `url`. That does not coincide with `delete` api.

Now I posted this on Rails and they requested me to create a test sample of my setup to debug this. When I did that, it's working using minitest, but not when I use rspec. It's possible that I do not have spec correctly configured to run in their stripped down rails controller which is where I need your help. Here's the extracted test sample:

```
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '5.0.0.rc1' #, github: 'rails/rails'
  gem 'rspec-rails', '~>3.1'
  gem 'bye bug'
end

require 'action_controller/railtie'

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.session_store :cookie_store, key: 'cookie_store_key'
  secrets.secret_token    = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    namespace :api do
      namespace :v0 do
        post '/subscribe', to: 'test#create'
        delete '/unsubscribe', to: 'test#destroy'
      end
    end
  end
end

module Api
  module V0
    class TestController < ActionController::API
      include Rails.application.routes.url_helpers

      def create
        render json: { action: 'Create', token: params["params"]["device_token"] }
      end

      def destroy
        render json: { action: 'Delete', token: params["params"]["device_token"] }
      end
    end
  end
end


require 'minitest/autorun'
require 'rack/test'

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_subscribe_returns_success
    post '/api/v0/subscribe', params: { device_token: "funny_token" }, headers: { "CONTENT_TYPE" => "application/json", "TOKEN" => "header_token" }
    assert last_response.ok?
    assert_equal last_response.body, "{\"action\":\"Create\",\"token\":\"funny_token\"}"
  end

  def test_unsubscribe_returns_success
    delete '/api/v0/unsubscribe', params: { device_token: "funny_token" }, headers: { "CONTENT_TYPE" => "application/json", "TOKEN" => "header_token" }

    assert last_response.ok?
    assert_equal last_response.body, "{\"action\":\"Delete\",\"token\":\"funny_token\"}"
  end

  private
    def app
      Rails.application
    end
end

#---------------------------------------
# Is this correctly configured?

require 'rspec/rails'
require 'rspec/autorun'

RSpec.describe "home page", :type => :request do
  it "subscribe_returns_success" do
    post '/api/v0/subscribe', params: { device_token: "funny_token" }, headers: { "CONTENT_TYPE" => "application/json", "TOKEN" => "header_token" }
    expect(response.status).to eq(200)
    # expect(response.body).to eq("Create - funny_token")
  end


  it "unsubscribe_returns_success" do
    delete '/api/v0/unsubscribe', params: { device_token: "funny_token" }, headers: { "CONTENT_TYPE" => "application/json", "TOKEN" => "header_token" }
    bye bug
    expect(response.status).to eq(200)
    # expect(response.body).to eq("Delete - funny_token")
  end
end

```

**Comment by JonRowe** [comment]
This is not an error:
```Ruby
Failure/Error: expect(response.status).to be(204)

       expected #<Fixnum:409> => 204
            got #<Fixnum:801> => 400
```
so it's useless to paste it, I was asking you to paste the backtrace of the delete error, which is provided by rails as your method source location shows, this is potentially a bug in our Rails 5 integration (you need to be using rspec-rails 3.5.0.beta3 for that by the way) or in your application source code. 

Your snippet fails as expected for me on the latest beta.

**Comment by JonRowe** [comment]
You also need to encode your json before sending it.

**Comment by hmistry** [comment]
I can't paste the backtrace for the `delete` error because that's done in `byebug`. But I did paste the backtrace as a result of that test failing.

Encode json before sending - I've never needed to do that in all my other `get`, `post`, `patch`, `delete` calls in tests which work fine, so I don't think that's the issue.

Lastly, I'm stuck in updating Rspec. It's one of the first things I tried after the basic debugging checks. Bundler will not let me install anything higher than v3.1 and I think guard-rspec(?) is preventing me though when I created a standalone `Gemfile` with only `guard-rspec`, then it used the latest Rspec v3.4.

This is the error when I try to force Rspec to v3.4:
```
Bundler could not find compatible versions for gem "spec-expectations":
  In Gemfile:
    guard-rspec was resolved to 4.7.0, which depends on
      rspec (< 4.0, >= 2.99.0) was resolved to 3.1.0, which depends on
        rspec-expectations (~> 3.1.0)

    rspec-rails (~> 3.4) was resolved to 3.4.0, which depends on
      rspec-expectations (~> 3.4.0)

```

**Comment by JonRowe** [comment]
You need `3.5.0.beta3` for Rails 5, which you'll have to specify directly, `~> 3.5.0.beta3` and then `bundle update guard-rspec rspec rspec-rails`

**Comment by hmistry** [comment]
Somehow the upgrade worked this time... yay! Rspec is now 3.5.0.beta3, but still same thing, `delete` request fails, while `post` & `get` requests are working.

**Comment by hmistry** [comment]
@JonRowe I revisited this today and you were right, the hash needed to be encoded into JSON when calling the request. I don't know what to say except I know I tried it along with many other things including trying to identify why `get` and `post` worked but `delete` didn't. I appreciate all your help and I'm sorry for troubling you with this.
