### ISSUE TITLE
OS X Sierra sqlite seg fault

### ISSUE THREAD

**Issue by killerham** [rspec/rspec-rails#1701]
I get the following error when running ```bundle exec guard``` after updating to os x sierra:

Notes:
Using Ruby 2.3.0, also tried 2.2.4 with same result. Running rspec on its own works fine.

```
18:11:21 - ERROR - Guard::RSpec cannot open results file: "/Users/my_account/my_app/tmp/rspec_guard_result". This is likely a bugso please report this at http://github.com/guard/guard-rspec/issues/new along with as muchinformation as possible to reproduce this issue.
18:11:21 - ERROR - Guard::RSpec failed to achieve its <run_on_modifications>, exception was:
> [#] Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/my_account/my_app/tmp/rspec_guard_result
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-rspec-4.7.3/lib/guard/rspec/results.rb:11:in `readlines'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-rspec-4.7.3/lib/guard/rspec/results.rb:11:in `initialize'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-rspec-4.7.3/lib/guard/rspec/rspec_process.rb:57:in `new'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-rspec-4.7.3/lib/guard/rspec/rspec_process.rb:57:in `_read_results'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-rspec-4.7.3/lib/guard/rspec/rspec_process.rb:18:in `initialize'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-rspec-4.7.3/lib/guard/rspec/runner.rb:65:in `new'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-rspec-4.7.3/lib/guard/rspec/runner.rb:65:in `_really_run'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-rspec-4.7.3/lib/guard/rspec/runner.rb:54:in `_run'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-rspec-4.7.3/lib/guard/rspec/runner.rb:38:in `run'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-rspec-4.7.3/lib/guard/rspec.rb:42:in `block in run_on_modifications'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-rspec-4.7.3/lib/guard/rspec.rb:48:in `_throw_if_failed'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-rspec-4.7.3/lib/guard/rspec.rb:42:in `run_on_modifications'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-2.14.0/lib/guard/runner.rb:82:in `block in _supervise'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-2.14.0/lib/guard/runner.rb:79:in `catch'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-2.14.0/lib/guard/runner.rb:79:in `_supervise'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-2.14.0/lib/guard/runner.rb:61:in `block (3 levels) in run_on_changes'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-2.14.0/lib/guard/runner.rb:56:in `each'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-2.14.0/lib/guard/runner.rb:56:in `block (2 levels) in run_on_changes'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-2.14.0/lib/guard/runner.rb:119:in `block (2 levels) in _run_group_plugins'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-2.14.0/lib/guard/runner.rb:117:in `each'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-2.14.0/lib/guard/runner.rb:117:in `block in _run_group_plugins'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-2.14.0/lib/guard/runner.rb:116:in `catch'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-2.14.0/lib/guard/runner.rb:116:in `_run_group_plugins'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-2.14.0/lib/guard/runner.rb:54:in `block in run_on_changes'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-2.14.0/lib/guard/runner.rb:53:in `each’
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-2.14.0/lib/guard/runner.rb:53:in `run_on_changes'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-2.14.0/lib/guard/internals/queue.rb:24:in `process'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-2.14.0/lib/guard/commander.rb:43:in `start'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-2.14.0/lib/guard/cli/environments/valid.rb:16:in `start_guard'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-2.14.0/lib/guard/cli.rb:122:in `start'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-2.14.0/lib/guard/aruba_adapter.rb:32:in `execute'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-2.14.0/lib/guard/aruba_adapter.rb:19:in `execute!'
> [#] /Users/my_account/.rvm/gems/ruby-2.3.0/gems/guard-2.14.0/bin/_guard-core:11:in `<main>'
```

Here is the stack trace from spring:

```
Running via Spring preloader in process 60048
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/sqlite3_adapter.rb:26: [BUG] Segmentation fault at 0x00000000000110
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:                    
     * ~/Library/Logs/CrashReporter                                         
     * /Library/Logs/CrashReporter                                          
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports.     

-- Control frame information -----------------------------------------------
c:0055 p:---- s:0217 e:000216 CFUNC  :initialize
c:0054 p:---- s:0215 e:000214 CFUNC  :new
c:0053 p:0186 s:0210 e:000209 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/sqlite3_adapter.rb:26
c:0052 p:0028 s:0203 e:000202 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:4
c:0051 p:0027 s:0200 e:000199 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:4
c:0050 p:0043 s:0196 e:000195 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:4
c:0049 p:0008 s:0192 e:000191 BLOCK  /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:3
c:0048 p:0015 s:0189 e:000188 METHOD /Users/my_account/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214
c:0047 p:0009 s:0186 e:000185 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:3
c:0046 p:0025 s:0183 e:000179 BLOCK  /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:2
c:0045 p:0015 s:0178 e:000177 METHOD /Users/my_account/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214
c:0044 p:0023 s:0175 e:000174 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:2
c:0043 p:0044 s:0172 e:000171 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:5
c:0042 p:0012 s:0166 e:000165 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_handling.rb:113
c:0041 p:0008 s:0163 e:000162 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_handling.rb:87
c:0040 p:0010 s:0160 e:000159 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:857
c:0039 p:0016 s:0156 e:000155 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:396
c:0038 p:0008 s:0153 e:000152 BLOCK  /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:411
c:0037 p:0025 s:0151 e:000150 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:642
c:0036 p:0031 s:0147 e:000146 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:416
c:0035 p:0025 s:0141 E:001e40 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:411
c:0034 p:0128 s:0138 e:000137 TOP    /Users/my_account/my_app/spec/rails_helper.rb:114 [FINISH]
c:0033 p:---- s:0136 e:000135 CFUNC  :require
c:0032 p:0012 s:0132 e:000131 BLOCK  /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274
c:0031 p:0059 s:0130 e:000129 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240
c:0030 p:0017 s:0125 e:000124 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274
c:0029 p:0010 s:0120 e:000119 BLOCK  /Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1394 [FINISH]
c:0028 p:---- s:0117 e:000116 CFUNC  :each
c:0027 p:0047 s:0114 e:000113 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1394
c:0026 p:0049 s:0109 e:000108 BLOCK  /Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration_options.rb:112 [FINISH]
c:0025 p:---- s:0106 e:000105 CFUNC  :each
c:0024 p:0029 s:0103 e:000102 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration_options.rb:111
c:0023 p:0010 s:0098 e:000097 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration_options.rb:21
c:0022 p:0048 s:0094 e:000093 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:99
c:0021 p:0012 s:0089 e:000088 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:86
c:0020 p:0085 s:0084 e:000083 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:71
c:0019 p:0026 s:0077 e:000076 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:45
c:0018 p:0025 s:0073 e:000072 TOP    /Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/exe/rspec:4 [FINISH]
c:0017 p:---- s:0071 e:000070 CFUNC  :load
c:0016 p:0014 s:0066 e:000065 BLOCK  /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268
c:0015 p:0059 s:0064 e:000063 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240
c:0014 p:0021 s:0059 e:000058 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268
c:0013 p:0101 s:0053 e:000052 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18
c:0012 p:0024 s:0050 e:000049 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/spring-1.7.2/lib/spring/command_wrapper.rb:38
c:0011 p:0204 s:0047 e:000046 BLOCK  /Users/my_account/.rvm/gems/ruby-2.3.0/gems/spring-1.7.2/lib/spring/application.rb:191 [FINISH]
c:0010 p:---- s:0045 e:000044 CFUNC  :fork
c:0009 p:0272 s:0042 e:000041 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/spring-1.7.2/lib/spring/application.rb:161
c:0008 p:0075 s:0029 e:000028 BLOCK  /Users/my_account/.rvm/gems/ruby-2.3.0/gems/spring-1.7.2/lib/spring/application.rb:131 [FINISH]
c:0007 p:---- s:0027 e:000026 CFUNC  :loop
c:0006 p:0028 s:0024 e:000023 METHOD /Users/my_account/.rvm/gems/ruby-2.3.0/gems/spring-1.7.2/lib/spring/application.rb:125
c:0005 p:0167 s:0021 E:0017d8 TOP    /Users/my_account/.rvm/gems/ruby-2.3.0/gems/spring-1.7.2/lib/spring/application/boot.rb:19 [FINISH]
c:0004 p:---- s:0018 e:000017 CFUNC  :require
c:0003 p:0124 s:0014 e:000013 METHOD /Users/my_account/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
c:0002 p:0008 s:0004 E:000150 EVAL   -e:1 [FINISH]
c:0001 p:0000 s:0002 E:000070 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
-e:1:in `<main>'
/Users/my_account/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/my_account/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/spring-1.7.2/lib/spring/application.rb:161:in `serve'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/spring-1.7.2/lib/spring/application.rb:161:in `fork'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/spring-1.7.2/lib/spring/application.rb:191:in `block in serve'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/spring-1.7.2/lib/spring/command_wrapper.rb:38:in `call'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/exe/rspec:4:in `<top (required)>'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:45:in `invoke'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:71:in `run'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:86:in `run'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:99:in `setup'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration_options.rb:21:in `configure'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration_options.rb:111:in `each'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1394:in `requires='
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1394:in `each'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1394:in `block in requires='
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/Users/my_account/my_app/spec/rails_helper.rb:114:in `<top (required)>'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:411:in `maintain_test_schema!'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:416:in `method_missing'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:642:in `suppress_messages'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:411:in `block in maintain_test_schema!'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:396:in `load_schema_if_pending!'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:857:in `needs_migration?'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_handling.rb:87:in `connection'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/Users/my_account/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/Users/my_account/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/sqlite3_adapter.rb:26:in `sqlite3_connection'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/sqlite3_adapter.rb:26:in `new'
/Users/my_account/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/sqlite3_adapter.rb:26:in `initialize'

-- Machine register context ------------------------------------------------
 rax: 0x0000000000000100 rbx: 0x00007fffb074b430 rcx: 0x0000000000000000
 rdx: 0x0000000000000000 rdi: 0x00007fffb07ae1c0 rsi: 0x00007ffadb6ceb60
 rbp: 0x00007fff5de02710 rsp: 0x00007fff5de026c8  r8: 0x00000000a40008ff
  r9: 0x00000000ffffffff r10: 0x0000000100000000 r11: 0x0000000000000000
 r12: 0x00007fffb07496d0 r13: 0x0000000000000000 r14: 0x00007ffadbd2f390
 r15: 0x00007ffadbd2f558 rip: 0x00007fffa7ac8943 rfl: 0x0000000000010206

-- C level backtrace information -------------------------------------------
0   libruby.2.3.0.dylib                 0x0000000101fa5b24 rb_vm_bugreport + 388
1   libruby.2.3.0.dylib                 0x0000000101e40aaa rb_bug_context + 490
2   libruby.2.3.0.dylib                 0x0000000101f159b4 sigsegv + 68
3   libsystem_platform.dylib            0x00007fffa7cf5bba _sigtramp + 26
4   libdispatch.dylib                   0x00007fffa7ac8943 _dispatch_queue_push + 171
5   libsqlite3.dylib                    0x00007fffa7692d78 fillInUnixFile + 568
6   libsqlite3.dylib                    0x00007fffa76929b0 unixOpen + 2192
7   libsqlite3.dylib                    0x00007fffa768e7f8 sqlite3BtreeOpen + 2856
8   libsqlite3.dylib                    0x00007fffa768a761 openDatabase + 1169
9   sqlite3_native.bundle               0x000000010369dd4f initialize + 799
10  libruby.2.3.0.dylib                 0x0000000101fa2924 vm_call0_body + 532
11  libruby.2.3.0.dylib                 0x0000000101fa31bd rb_call0 + 397
12  libruby.2.3.0.dylib                 0x0000000101ea27b9 rb_class_new_instance + 41
13  libruby.2.3.0.dylib                 0x0000000101f9be2a vm_call_cfunc + 314
14  libruby.2.3.0.dylib                 0x0000000101f8631a vm_exec_core + 10186
15  libruby.2.3.0.dylib                 0x0000000101f96643 vm_exec + 131
16  libruby.2.3.0.dylib                 0x0000000101e4d1e0 rb_load_internal0 + 288
17  libruby.2.3.0.dylib                 0x0000000101e4daa5 rb_require_internal + 1829
18  libruby.2.3.0.dylib                 0x0000000101e4d268 rb_f_require + 24
19  libruby.2.3.0.dylib                 0x0000000101f9be2a vm_call_cfunc + 314
20  libruby.2.3.0.dylib                 0x0000000101f8659f vm_exec_core + 10831
21  libruby.2.3.0.dylib                 0x0000000101f96643 vm_exec + 131
22  libruby.2.3.0.dylib                 0x0000000101f91cd7 rb_yield + 183
23  libruby.2.3.0.dylib                 0x0000000101dff0e9 rb_ary_each + 41
24  libruby.2.3.0.dylib                 0x0000000101f9be2a vm_call_cfunc + 314
25  libruby.2.3.0.dylib                 0x0000000101f860e0 vm_exec_core + 9616
26  libruby.2.3.0.dylib                 0x0000000101f96643 vm_exec + 131
27  libruby.2.3.0.dylib                 0x0000000101f91cd7 rb_yield + 183
28  libruby.2.3.0.dylib                 0x0000000101dff0e9 rb_ary_each + 41
29  libruby.2.3.0.dylib                 0x0000000101f9be2a vm_call_cfunc + 314
30  libruby.2.3.0.dylib                 0x0000000101f860e0 vm_exec_core + 9616
31  libruby.2.3.0.dylib                 0x0000000101f96643 vm_exec + 131
32  libruby.2.3.0.dylib                 0x0000000101e4d1e0 rb_load_internal0 + 288
33  libruby.2.3.0.dylib                 0x0000000101e4e04f rb_f_load + 159
34  libruby.2.3.0.dylib                 0x0000000101f9be2a vm_call_cfunc + 314
35  libruby.2.3.0.dylib                 0x0000000101f8659f vm_exec_core + 10831
36  libruby.2.3.0.dylib                 0x0000000101f96643 vm_exec + 131
37  libruby.2.3.0.dylib                 0x0000000101f91cd7 rb_yield + 183
38  libruby.2.3.0.dylib                 0x0000000101e4a35a rb_protect + 250
39  libruby.2.3.0.dylib                 0x0000000101ecdd4d rb_f_fork + 93
40  libruby.2.3.0.dylib                 0x0000000101f9be2a vm_call_cfunc + 314
41  libruby.2.3.0.dylib                 0x0000000101f860e0 vm_exec_core + 9616
42  libruby.2.3.0.dylib                 0x0000000101f96643 vm_exec + 131
43  libruby.2.3.0.dylib                 0x0000000101fa4260 loop_i + 48
44  libruby.2.3.0.dylib                 0x0000000101e4a118 rb_rescue2 + 280
45  libruby.2.3.0.dylib                 0x0000000101f9be2a vm_call_cfunc + 314
46  libruby.2.3.0.dylib                 0x0000000101f860e0 vm_exec_core + 9616
47  libruby.2.3.0.dylib                 0x0000000101f96643 vm_exec + 131
48  libruby.2.3.0.dylib                 0x0000000101e4d1e0 rb_load_internal0 + 288
49  libruby.2.3.0.dylib                 0x0000000101e4daa5 rb_require_internal + 1829
50  libruby.2.3.0.dylib                 0x0000000101e4d268 rb_f_require + 24
51  libruby.2.3.0.dylib                 0x0000000101f9be2a vm_call_cfunc + 314
52  libruby.2.3.0.dylib                 0x0000000101f8631a vm_exec_core + 10186
53  libruby.2.3.0.dylib                 0x0000000101f96643 vm_exec + 131
54  libruby.2.3.0.dylib                 0x0000000101e494f8 ruby_exec_internal + 152
55  libruby.2.3.0.dylib                 0x0000000101e49406 ruby_run_node + 54
56  ruby                                0x0000000101df7f2f main + 79
```

**Comment by myronmarston** [comment]
Sqlite is not maintained by the RSpec maintainers, so we cannot help troubleshooting segfaults in it.  Please report this to the Sqlite maintainers instead.

**Comment by killerham** [comment]
Whoops I put this in the wrong tab! Sorry about that.
