### ISSUE TITLE
rspec-rails without ActiveRecord on Rails 4.2

### ISSUE THREAD

**Issue by HarlemSquirrel** [rspec/rspec-rails#1819]
I'm slimming down a rails app that is not using ActiveRecord by removing it along with ActionMailer. The app works fine in development and when running `RAILS_ENV=test rails s` but my specs are failing with the following.

```
Failure/Error: raise ConnectionNotEstablished, "No connection pool for #{klass}" unless pool
     
     ActiveRecord::ConnectionNotEstablished:
       No connection pool for ActiveRecord::Base
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:570:in `retrieve_connection'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/activerecord-4.2.8/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/activerecord-4.2.8/lib/active_record/connection_handling.rb:87:in `connection'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/activerecord-4.2.8/lib/active_record/fixtures.rb:501:in `create_fixtures'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/activerecord-4.2.8/lib/active_record/fixtures.rb:979:in `load_fixtures'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/activerecord-4.2.8/lib/active_record/fixtures.rb:952:in `setup_fixtures'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/activerecord-4.2.8/lib/active_record/fixtures.rb:826:in `before_setup'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-rails-3.6.0/lib/rspec/rails/adapters.rb:126:in `block in MinitestLifecycleAdapter'
     # org/jruby/RubyBasicObject.java:1724:in `instance_exec'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:375:in `execute_with'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:606:in `block in run_around_example_hooks_for'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:342:in `call'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:605:in `run_around_example_hooks_for'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:464:in `run'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:251:in `run'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:627:in `block in run_examples'
     # org/jruby/RubyArray.java:2485:in `map'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:623:in `run_examples'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:589:in `run'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:118:in `block in run_specs'
     # org/jruby/RubyArray.java:2485:in `map'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:118:in `block in run_specs'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1894:in `with_suite_hooks'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:113:in `block in run_specs'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/lib/rspec/core/reporter.rb:79:in `report'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:112:in `run_specs'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:87:in `run'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:71:in `run'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:45:in `invoke'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/gems/rspec-core-3.6.0/exe/rspec:4:in `<main>'
     # org/jruby/RubyKernel.java:979:in `load'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/bin/rspec:1:in `<eval>'
     # org/jruby/RubyKernel.java:1000:in `eval'
     # /home/kmack/.rvm/gems/jruby-9.1.7.0/bin/jruby_executable_hooks:15:in `<main>'
     # 
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.

```

Here's my configuration files...

```ruby
# rails_helper.rb

# This file is copied to spec/ when you run 'rails generate rspec:install'
require 'spec_helper'
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
# Prevent database truncation if the environment is production
abort("The Rails environment is running in production mode!") if Rails.env.production?
require 'rspec/rails'
# Add additional requires below this line. Rails is not loaded until this point!

require 'capybara/rails'
require 'capybara/rspec'

require_relative 'support/capybara'
require_relative 'support/cleanup'
require_relative 'support/when_authenticated'
# Requires supporting ruby files with custom matchers and macros, etc, in
# spec/support/ and its subdirectories. Files matching `spec/**/*_spec.rb` are
# run as spec files by default. This means that files in spec/support that end
# in _spec.rb will both be required and run as specs, causing the specs to be
# run twice. It is recommended that you do not name files matching this glob to
# end with _spec.rb. You can configure this pattern with the --pattern
# option on the command line or in ~/.rspec, .rspec or `.rspec-local`.
#
# The following line is provided for convenience purposes. It has the downside
# of increasing the boot-up time by auto-requiring all files in the support
# directory. Alternatively, in the individual `*_spec.rb` files, manually
# require only the support files necessary.
#
# Dir[Rails.root.join('spec/support/**/*.rb')].each { |f| require f }

# Checks for pending migration and applies them before tests are run.
# If you are not using ActiveRecord, you can remove this line.
# ActiveRecord::Migration.maintain_test_schema!

RSpec.configure do |config|
  # Remove this line if you're not using ActiveRecord or ActiveRecord fixtures
  # config.fixture_path = "#{::Rails.root}/spec/fixtures"

  # If you're not using ActiveRecord, or you'd prefer not to run each of your
  # examples within a transaction, remove the following line or assign false
  # instead of true.
  # config.use_transactional_fixtures = true

  # RSpec Rails can automatically mix in different behaviours to your tests
  # based on their file location, for example enabling you to call `get` and
  # `post` in specs under `spec/controllers`.
  #
  # You can disable this behaviour by removing the line below, and instead
  # explicitly tag your specs with their type, e.g.:
  #
  #     RSpec.describe UsersController, :type => :controller do
  #       # ...
  #     end
  #
  # The different available types are documented in the features, such as in
  # https://relishapp.com/rspec/rspec-rails/docs
  config.infer_spec_type_from_file_location!

  # Filter lines from Rails gems in backtraces.
  config.filter_rails_from_backtrace!
  # arbitrary gems may also be filtered via:
  # config.filter_gems_from_backtrace("gem name")
end
```

```ruby
# spec_helper.rb

# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata. When nothing
  # is tagged with `:focus`, all examples get run. RSpec also provides
  # aliases for `it`, `describe`, and `context` that include `:focus`
  # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  #   - http://rspec.info/blog/2012/06/rspecs-new-expectation-syntax/
  #   - http://www.teaisaweso.me/blog/2013/05/27/rspecs-new-message-expectation-syntax/
  #   - http://rspec.info/blog/2014/05/notable-changes-in-rspec-3/#zero-monkey-patching-mode
  config.disable_monkey_patching!

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = "doc"
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 3

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed
end

```

**Comment by JonRowe** [comment]
So something is triggering the inclusion of ActiveRecord transactional fixtures, check your gems and code, this is unlikely to be something within RSpec.

**Comment by HarlemSquirrel** [comment]
For whatever reason, it seems to be working now. Thanks!

**Comment by danhawkins** [comment]
I have this issue at the moment, but it won't start working for me @HarlemSquirrel which version are you using?

**Comment by HarlemSquirrel** [comment]
@danhawkins This app has since been updated to Rails 5.1 and rspec-rails 3.7.1

**Comment by ypicard** [comment]
Same probleme here...  @danhawkins how did you solve your problem ?
