### ISSUE TITLE
Arbitrary param on the route forces me to inform this same param on the test

### ISSUE THREAD

**Issue by paniko0** [rspec/rspec-rails#1824]
Hi guys,

given that I have a route like this:

```
get "/bla", to: "bla#index", some_arbitrary_param: "AA"
```

Then I have to specify `some_arbitrary_param` on my spec, like this:

```
get :index, some_arbitrary_param: "AA"
```

If I don't specify, I get the following error:

```
Failure/Error: get :index
     ActionController::UrlGenerationError:
       No route matches {:action=>"index", :controller=>"bla"}
     # /Users/me/.rvm/gems/ruby-2.3.1@rspec-test-project/gems/actionpack-4.2.0/lib/action_dispatch/journey/formatter.rb:46:in `generate'
     # /Users/me/.rvm/gems/ruby-2.3.1@rspec-test-project/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:710:in `generate'
     # /Users/me/.rvm/gems/ruby-2.3.1@rspec-test-project/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:741:in `generate'
     # /Users/me/.rvm/gems/ruby-2.3.1@rspec-test-project/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:736:in `generate_extras'
     # /Users/me/.rvm/gems/ruby-2.3.1@rspec-test-project/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:731:in `extra_keys'
     # /Users/me/.rvm/gems/ruby-2.3.1@rspec-test-project/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:205:in `assign_parameters'
     # /Users/me/.rvm/gems/ruby-2.3.1@rspec-test-project/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:616:in `process'
     # /Users/me/.rvm/gems/ruby-2.3.1@rspec-test-project/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:65:in `process'
     # /Users/me/.rvm/gems/ruby-2.3.1@rspec-test-project/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:505:in `get'
```

The weird thing is that I have access to this arbitrary parameter if I request on my browser, but when it comes to the test, I have to specify it as a parameter.

Do you guys have any idea about why do I have to pass it as a param?

**Comment by JonRowe** [comment]
This is a routing resolution issue upstream in Rails, please ask them.
