### ISSUE TITLE
posting raw JSON bodies not possible without using positional arguments - rails 5.2.3, rspec 3.8

### ISSUE THREAD

**Issue by Rio517** [rspec/rspec-rails#1852]
It is possible to `post` json bodies without using positional arguments in rspec version 3.6.0 on rails 5.0.5

I saw @JonRowe 's recommendation in https://github.com/rspec/rspec-rails/issues/1650, but this dosen't  actually populate the body when I am reading it from the controller.

`post '/some_endpoint', body:  {id:  1}.to_json, format: :json` 
`request.body.read` returns a query string => `body=%7B%22id%22%3A1%7D&format=json`

`post '/some_endpoint', {id:  1}.to_json, format: :json` 
`request.body.read`  => `{"id":1}` but raises the warning:

```
Using positional arguments in integration tests has been deprecated,
in favor of keyword arguments, and will be removed in Rails 5.1
```
My gemfile.lock:
```
    rspec-rails (3.6.0)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.6.0)
      rspec-expectations (~> 3.6.0)
      rspec-mocks (~> 3.6.0)
      rspec-support (~> 3.6.0)
```

**Comment by coding-bunny** [comment]
I'm running into similar problems actually, and I'm also looking for a way around this.
I'm trying to post a JSON body that has an array as top level object (see https://github.com/rspec/rspec-core/issues/2458).

# Test Setup
```
let(:endpoint_json) do
  [
      {
        "source_subregion": 'Oklahoma',
        "source_reach": 0,
        "source_name": 'Norman Observer',
        "source_information_type": 'news',
        "source_country_code": 'us',
        "metadata": {
          "search_name": '01) Supplier',
          "search_id": 2_727_969,
          "hook_id": 'f77ab22ba62684b35a3743ce6f41f18d800e977b'
        },
        "document_url": 'http://normanobserver.com/analysts-see-2-03-eps-for-watsco-wso-denver-investment-advisors-trimmed-agilent-technologies-a-holding/',
        "document_title": 'Analysts See $2.03 EPS for Watsco (WSO), Denver Investment Advisors Trimmed Agilent Technologies (A) Holding',
        "document_sentiment": 'neutral',
        "document_publish_date": '2017-07-19T10:26:27.937Z',
        "document_opening_text": 'Denver Investment Advisors Llc decreased Agilent Technologies Inc (A) stake by 27.36% reported in 2016Q4 SEC filing. Denver Investment...',
        "document_matched_keywords": ['A in', 'Buy', 'firm'],
        "document_language_code": 'en',
        "document_key_phrases": [
          { "relevance": 0.8547191703197672, "phrase": '” rating'},
          { "relevance": 0.8386967921058046, "phrase": 'Watsco Inc’s analysts' },
          { "relevance": 0.8232013419439597, "phrase": 'Agilent Technologies Inc' },
          { "relevance": 0.8147191703197671, "phrase": 'Buy” rating' },
          { "relevance": 0.799491900000467, "phrase": 'stock' },
          { "relevance": 0.7983554547916699, "phrase": 'shares' },
          { "relevance": 0.7959034696485439, "phrase": 'Analysts' },
          { "relevance": 0.7776051777228943, "phrase": 'Watsco Inc' },
          { "relevance": 0.6676763159365867, "phrase": 'equipment products' },
          { "relevance": 0.6430989199874523, "phrase": 'Kalmar Investments Inc De' }
        ],
        "document_image_link": 'http://normanobserver.com/wp-content/uploads/2017/07/WSO-Chart.jpg',
        "document_id": 'fThrkvtoal3MTu4-A4uNIMJppDY',
        "document_hit_sentence": '” rating. Deutsche Bank initiated the shares of A in report on Wednesday, January 18 with “Buy” rating. The firm has “Outperform” rating by',
        "document_author": 'Richard Conner'
      }
    ]
end
```

The above snippet is basically the JSON we are receiving from an endpoint that makes callbacks to our application. So I wanted to write a test for my controller to check whether the implementation is done correctly.
However this turns out to be no small feat actually.
I based myself on the [RSpec Documentation](https://relishapp.com/rspec/rspec-rails/docs/request-specs/request-spec#providing-json-data)

# Attempt 1
```
it 'creates a new instance of my object` do
  expect do
    post :create, params: endpoint_json.to_json, headers: { 'CONTENT_TYPE' => 'application/json', 'ACCEPT' => 'application/json' }
   end.to(change { MyObject.count }.by(1))
end
```

Except this doesn't work because it raises the following error for me:

```
NoMethodError: undefined method `symbolize_keys' for #<String:0x007feb2b073f00>
```

# Attempt 2
Okay fine, so it doesn't like the string to be injected directly.
Can we just give it the object and trust RSpec and Rspec-Rails to convert it for us?

```
it 'creates a new instance of my object` do
  expect do
    post :create, params: endpoint_json., headers: { 'CONTENT_TYPE' => 'application/json', 'ACCEPT' => 'application/json' }
   end.to(change { MyObject.count }.by(1))
end
```

Apparently not:

```
NoMethodError: undefined method `symbolize_keys' for #<Array:0x007fd79daa5d80>
```

# Attempt 3
Okay, perhaps the code is getting confused with which parameter goes where...

```
it 'creates a new instance of my object` do
  expect do
    post :create, { params: endpoint_json }, { headers: { 'CONTENT_TYPE' => 'application/json', 'ACCEPT' => 'application/json' } }
   end.to(change { MyObject.count }.by(1))
end
```

This got rid of the errors at least, but introduces a different problem.
Breaking into the controller, and looking at the data received, this is what the console shows:

```
request.format
=> #<Mime::Type:0x007f85b88d03e8 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=3390589049612789453>

0> request.content_type
=> "application/x-www-form-urlencoded"

0> params
=> <ActionController::Parameters {"params"=>[{"document_author"=>"Richard Conner", "document_hit_sentence"=>"” rating. Deutsche Bank initiated the shares of A in report on Wednesday, January 18 with “Buy” rating. The firm has “Outperform” rating by", "document_id"=>"fThrkvtoal3MTu4-A4uNIMJppDY", "document_image_link"=>"http://normanobserver.com/wp-content/uploads/2017/07/WSO-Chart.jpg", "document_key_phrases"=>[{"phrase"=>"” rating", "relevance"=>"0.8547191703197672"}, {"phrase"=>"Watsco Inc’s analysts", "relevance"=>"0.8386967921058046"}, {"phrase"=>"Agilent Technologies Inc", "relevance"=>"0.8232013419439597"}, {"phrase"=>"Buy” rating", "relevance"=>"0.8147191703197671"}, {"phrase"=>"stock", "relevance"=>"0.799491900000467"}, {"phrase"=>"shares", "relevance"=>"0.7983554547916699"}, {"phrase"=>"Analysts", "relevance"=>"0.7959034696485439"}, {"phrase"=>"Watsco Inc", "relevance"=>"0.7776051777228943"}, {"phrase"=>"equipment products", "relevance"=>"0.6676763159365867"}, {"phrase"=>"Kalmar Investments Inc De", "relevance"=>"0.6430989199874523"}], "document_language_code"=>"en", "document_matched_keywords"=>["A in", "Buy", "firm"], "document_opening_text"=>"Denver Investment Advisors Llc decreased Agilent Technologies Inc (A) stake by 27.36% reported in 2016Q4 SEC filing. Denver Investment...", "document_publish_date"=>"2017-07-19T10:26:27.937Z", "document_sentiment"=>"neutral", "document_title"=>"Analysts See $2.03 EPS for Watsco (WSO), Denver Investment Advisors Trimmed Agilent Technologies (A) Holding", "document_url"=>"http://normanobserver.com/analysts-see-2-03-eps-for-watsco-wso-denver-investment-advisors-trimmed-agilent-technologies-a-holding/", "metadata"=>{"hook_id"=>"f77ab22ba62684b35a3743ce6f41f18d800e977b", "search_id"=>"2727969", "search_name"=>"01) Supplier"}, "source_country_code"=>"us", "source_information_type"=>"news", "source_name"=>"Norman Observer", "source_reach"=>"0", "source_subregion"=>"Oklahoma"}], "controller"=>"callbacks", "action"=>"create"} permitted: false>

0> params[:params]
=> [
  <ActionController::Parameters {
    "document_author"=>"Richard Conner",
    "document_hit_sentence"=>"” rating. Deutsche Bank initiated the shares of A in report on Wednesday, January 18 with “Buy” rating. The firm has “Outperform” rating by", 
    "document_id"=>"fThrkvtoal3MTu4-A4uNIMJppDY", 
   "document_image_link"=>"http://normanobserver.com/wp-content/uploads/2017/07/WSO-Chart.jpg", 
   "document_key_phrases"=>[
      {"phrase"=>"” rating", "relevance"=>"0.8547191703197672"},
      {"phrase"=>"Watsco Inc’s analysts", "relevance"=>"0.8386967921058046"}, 
      {"phrase"=>"Agilent Technologies Inc", "relevance"=>"0.8232013419439597"}, 
      {"phrase"=>"Buy” rating", "relevance"=>"0.8147191703197671"},
      {"phrase"=>"stock", "relevance"=>"0.799491900000467"}, {"phrase"=>"shares", "relevance"=>"0.7983554547916699"},
      {"phrase"=>"Analysts", "relevance"=>"0.7959034696485439"},
      {"phrase"=>"Watsco Inc", "relevance"=>"0.7776051777228943"},
      {"phrase"=>"equipment products", "relevance"=>"0.6676763159365867"}, 
      {"phrase"=>"Kalmar Investments Inc De", "relevance"=>"0.6430989199874523"}], 
   "document_language_code"=>"en",
   "document_matched_keywords"=>["A in", "Buy", "firm"],
   "document_opening_text"=>"Denver Investment Advisors Llc decreased Agilent Technologies Inc (A) stake by 27.36% reported in 2016Q4 SEC filing. Denver Investment...", 
   "document_publish_date"=>"2017-07-19T10:26:27.937Z",
   "document_sentiment"=>"neutral",
   "document_title"=>"Analysts See $2.03 EPS for Watsco (WSO), Denver Investment Advisors Trimmed Agilent Technologies (A) Holding", 
   "document_url"=>"http://normanobserver.com/analysts-see-2-03-eps-for-watsco-wso-denver-investment-advisors-trimmed-agilent-technologies-a-holding/",
   "metadata"=>{
      "hook_id"=>"f77ab22ba62684b35a3743ce6f41f18d800e977b",
      "search_id"=>"2727969",
      "search_name"=>"01) Supplier"
     },
    "source_country_code"=>"us",
    "source_information_type"=>"news",
    "source_name"=>"Norman Observer",
    "source_reach"=>"0", 
    "source_subregion"=>"Oklahoma"} permitted: false>]
```
The problems:
* The headers I injected are completely ignored by Rails or not passed through. I submitted JSON, not url-form-encoded content
* The parameters are weird. I expect my `params` hash to represent what I submitted, not this nested StrongParamter structure again. I can work with it, but it feels wrong.
* The way I had to write my spec is going against the documentation and ruby way. I have to be too specific to get something going and it feels wrong.

**Comment by coding-bunny** [comment]
# Update
I've changed my spec into the following:

```
  describe '#create' do
    it 'creates a new research-hit with the provided data' do
      expect do
        headers = { CONTENT_TYPE: 'application/json', ACCEPT: 'application/json' }
        post :create, body: meltwater_data.to_json, headers: headers
      end.to(change { ResearchHit::Hit.count }.by(1))
    end
  end
```

But this forces me to do the following in my controller:

```
  def create
    formatted_data.each do |data|
      form_factory.hit_form(extract_data(data)).create
    end

    head(:created)
  rescue StandardError => e
    Rails.logger.error(message: 'Failed to parse Meltwater Callback', error: e.message)
    head(:bad_request)
  end

  protected

  # Parses the raw body of the request as JSON.
  # If this fails for whatever reason, the action will return a Bad Request response.
  # Need to do it this way because Rails apparently cannot do this properly on it's own.
  def formatted_data
    JSON.parse(request.raw_post, symbolize_names: true)
  end

  # Extracts the information from the posted data set needed to properly construct ResearchHit object.
  # The information is based on the original ::ResearchHub::Meltwater::MailImporter, tweaked for the structure we need.
  def extract_data(data)
    {
      research_source_id: ::ResearchSource.meltwater.id,
      category: data[:source_information_type],
      topic: data[:document_title],
      source: data[:source_name],
      message: data[:document_opening_text],
      keywords: data[:document_key_phrases].map { |x| x[:phrase] }.flatten,
      link: data[:document_url]
    }
  end
```

Because otherwise I simply cannot rely on Rails to get me the data in a convenient way.
Is this really the way to do this?

**Comment by MiguelSavignano** [comment]
Hi @coding-bunny this works for me to send JSON array in body

Example:
```
curl -X POST -H 'Content-type: application/json' localhost:3000/create_posts -d  '[ { "title": 'title' } ]'
```

When i send array in de body rails parse the body like this

```
<ActionController::Parameters {"_json"=>[{"title"=> "title"}], "controller"=>"posts", "action"=>"create_posts" } permitted: false>
```


This works for me in Controller test

```ruby
      it "returns http success" do
        post :create_posts, params: { _json: [ { title: 'title' } ] }
        expect(response).to have_http_status(:success)
      end
```

**Comment by Rio517** [comment]
Take a closer look at the posted request in your test case.  Here is an example request spec, but I believe the gist of it is:

https://github.com/Rio517/rspec-example-issue-1852

```
 context 'with params' do
      it 'receives a body' do
        sample_body = {data: {title: 'book title', author: 'John Doe'}}
        post :create, params: sample_body
        expect(response).to have_http_status(:success)
        expect(response.body).to eq(sample_body.to_json.to_s)
      end
    end
```

which results in:
```
  1) BooksController#show with params with params receives a body
     Failure/Error: expect(response.body).to eq(sample_body.to_json.to_s)
     
       expected: "{\"data\":{\"title\":\"book title\",\"author\":\"John Doe\"}}"
            got: "data%5Bauthor%5D=John+Doe&data%5Btitle%5D=book+title"
     
       (compared using ==)
     # ./spec/controllers/books_controller_spec.rb:13:in `block (4 levels) in <top (required)>'

  2) Books #show with params with params receives a body
     Failure/Error: expect(response.body).to eq(sample_body.to_json.to_s)
     
       expected: "{\"data\":{\"title\":\"book title\",\"author\":\"John Doe\"}}"
            got: "data[title]=book+title&data[author]=John+Doe"
     
       (compared using ==)
     # ./spec/requests/books_spec.rb:13:in `block (4 levels) in <top (required)>'

```
```

**Comment by Rio517** [comment]
Related: If you extend this case to try to pass a json string to params in a controller spec, you get an error. Seems params expects a hash. This effectively leaves one with no way to json in the body - at least that I'm aware of. See: https://github.com/Rio517/rspec-example-issue-1852/commit/9ac54a1a9afbe5019ab1329464a2dd3daf427bc4

**Comment by JonRowe** [comment]
The format of the options used depends on your Rails version, its all Rails code. You usually need to tell Rails its json you are sending with `format: :json` or `as: :json`
