### ISSUE TITLE
Error on update rack-test from 0.7.0 to 0.7.1

### ISSUE THREAD

**Issue by 007lva** [rspec/rspec-rails#1915]
With rspec-rails 3.7.2

```
     NoMethodError:
       undefined method `size' for nil:NilClass
     # /home/lvargas/.gem/ruby/2.4.1/gems/rack-test-0.7.1/lib/rack/test/uploaded_file.rb:38:in `public_send'
     # /home/lvargas/.gem/ruby/2.4.1/gems/rack-test-0.7.1/lib/rack/test/uploaded_file.rb:38:in `method_missing'
     # /home/lvargas/.gem/ruby/2.4.1/gems/rack-test-0.7.1/lib/rack/test/utils.rb:136:in `build_file_part'
     # /home/lvargas/.gem/ruby/2.4.1/gems/rack-test-0.7.1/lib/rack/test/utils.rb:101:in `block in get_parts'
     # /home/lvargas/.gem/ruby/2.4.1/gems/rack-test-0.7.1/lib/rack/test/utils.rb:92:in `each'
     # /home/lvargas/.gem/ruby/2.4.1/gems/rack-test-0.7.1/lib/rack/test/utils.rb:92:in `map'
     # /home/lvargas/.gem/ruby/2.4.1/gems/rack-test-0.7.1/lib/rack/test/utils.rb:92:in `get_parts'
     # /home/lvargas/.gem/ruby/2.4.1/gems/rack-test-0.7.1/lib/rack/test/utils.rb:97:in `block (2 levels) in get_parts'
     # /home/lvargas/.gem/ruby/2.4.1/gems/rack-test-0.7.1/lib/rack/test/utils.rb:94:in `map'
     # /home/lvargas/.gem/ruby/2.4.1/gems/rack-test-0.7.1/lib/rack/test/utils.rb:94:in `block in get_parts'
     # /home/lvargas/.gem/ruby/2.4.1/gems/rack-test-0.7.1/lib/rack/test/utils.rb:92:in `each'
     # /home/lvargas/.gem/ruby/2.4.1/gems/rack-test-0.7.1/lib/rack/test/utils.rb:92:in `map'
     # /home/lvargas/.gem/ruby/2.4.1/gems/rack-test-0.7.1/lib/rack/test/utils.rb:92:in `get_parts'
     # /home/lvargas/.gem/ruby/2.4.1/gems/rack-test-0.7.1/lib/rack/test/utils.rb:87:in `build_parts'
     # /home/lvargas/.gem/ruby/2.4.1/gems/rack-test-0.7.1/lib/rack/test/utils.rb:77:in `build_multipart'
     # /home/lvargas/.gem/ruby/2.4.1/gems/rack-test-0.7.1/lib/rack/test.rb:231:in `env_for'
     # /home/lvargas/.gem/ruby/2.4.1/gems/rack-test-0.7.1/lib/rack/test.rb:128:in `custom_request'
     # /home/lvargas/.gem/ruby/2.4.1/gems/rack-test-0.7.1/lib/rack/test.rb:66:in `post'
     # /home/lvargas/.gem/ruby/2.4.1/gems/capybara-2.16.0/lib/capybara/rack_test/browser.rb:69:in `process'
     # /home/lvargas/.gem/ruby/2.4.1/gems/capybara-2.16.0/lib/capybara/rack_test/browser.rb:41:in `process_and_follow_redirects'
     # /home/lvargas/.gem/ruby/2.4.1/gems/capybara-2.16.0/lib/capybara/rack_test/browser.rb:32:in `submit'
     # /home/lvargas/.gem/ruby/2.4.1/gems/capybara-2.16.0/lib/capybara/rack_test/form.rb:78:in `submit'
     # /home/lvargas/.gem/ruby/2.4.1/gems/capybara-2.16.0/lib/capybara/rack_test/node.rb:64:in `click'
     # /home/lvargas/.gem/ruby/2.4.1/gems/capybara-2.16.0/lib/capybara/node/element.rb:143:in `block in click'
     # /home/lvargas/.gem/ruby/2.4.1/gems/capybara-2.16.0/lib/capybara/node/base.rb:85:in `synchronize'
     # /home/lvargas/.gem/ruby/2.4.1/gems/capybara-2.16.0/lib/capybara/node/element.rb:143:in `click'
     # /home/lvargas/.gem/ruby/2.4.1/gems/capybara-2.16.0/lib/capybara/node/actions.rb:61:in `click_button'
     # /home/lvargas/.gem/ruby/2.4.1/gems/capybara-2.16.0/lib/capybara/session.rb:810:in `block (2 levels) in <class:Session>'
     # /home/lvargas/.gem/ruby/2.4.1/gems/capybara-2.16.0/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
```

but works well with rack-test-0.7.0, I'm not sure if I should report this also to rack-test.

**Comment by JonRowe** [comment]
From the stack trace here I'd say you need to raise this with `rack-test`

**Comment by 007lva** [comment]
Ok, thanks!

**Comment by Schwad** [comment]
In 2018 I got this exact error when upgrading to Rails 5.2.0.rc1. Glad to know I'm not alone!
