### ISSUE TITLE
uninitialized constant RSpec::Mocks::ExampleMethods

### ISSUE THREAD

**Issue by mockdeep** [rspec/rspec-rails#2309]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.5.3
Rails version: 5.2.4.2
RSpec 3.9
  - rspec-core 3.9.1
  - rspec-expectations 3.9.1
  - rspec-mocks 3.9.1
  - rspec-rails 4.0.0
  - rspec-support 3.9.2

## Observed behaviour

In one of our test helpers, we have the following:

```rb
class FeatureFlow
  include RSpec::Matchers, RSpec::Mocks::ExampleMethods, Capybara::DSL
 
  ...
end
```

When this class loads during the test bootup, we get the following error:

```
NameError:
  uninitialized constant RSpec::Mocks::ExampleMethods
# /home/fletch/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant'
# /home/fletch/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:9:in `without_bootsnap_cache'
# /home/fletch/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `rescue in load_missing_constant'
# /home/fletch/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
# ./spec/features/_support/feature_flow.rb:4:in `<class:FeatureFlow>'
# ./spec/features/_support/feature_flow.rb:3:in `<top (required)>'
# /home/fletch/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
# /home/fletch/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
# /home/fletch/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
# /home/fletch/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
# /home/fletch/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
# ./spec/rails_helper.rb:33:in `block in <top (required)>'
# ./spec/rails_helper.rb:33:in `each'
# ./spec/rails_helper.rb:33:in `<top (required)>'
# ------------------
# --- Caused by: ---
# NameError:
#   uninitialized constant RSpec::Mocks::ExampleMethods
#   /home/fletch/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant'
```

Rails helper, up to line 33 looks like:

```rb
# frozen_string_literal: true

require 'rubygems'
require 'simplecov'
require 'vcr'

SimpleCov.coverage_dir('coverage/simplecov')
SimpleCov.start :rails do
  add_filter 'lib/mailer_previews'
end

SimpleCov.minimum_coverage(100) if ENV['CI'] && !ENV['SLOW']

# This file is copied to spec/ when you run 'rails generate rspec:install'
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../config/environment', __dir__)
def spec_root
  @spec_root ||= Rails.root.join('spec')
end

require 'rspec'
require 'rspec/rails'
require 'capybara/rspec'
require 'capybara-screenshot/rspec'
require 'sidekiq'
require 'sidekiq/testing/inline'
require 'sidekiq-status/testing/inline'
require 'paper_trail/frameworks/rspec'

Dir[spec_root.join('_shared_examples', '*.rb')].each { |f| require f }
Dir[spec_root.join('_shared_context', '*.rb')].each { |f| require f }
Dir[spec_root.join('support', '*.rb')].each { |f| require f }
Dir[spec_root.join('features', '_support', '*.rb')].each { |f| require f }
```

## Expected behaviour

We should be able to include the module `RSpec::Mocks::ExampleMethods`. This works in `rspec-rails` 3.9.1, but not in 4.0.0. If I add `require 'rspec/mocks'` above that line it does seem to work fine. But this seems like some sort of regression.

## Can you provide an example app?

Sorry, no.

**Comment by JonRowe** [comment]
Did you restart bootsnap after upgrading?

**Comment by JonRowe** [comment]
Closing as this isn't an issue with `rspec-rails` but with how bundler require / Rails is autoloading files / constants, `rspec-rails` itself never uses `RSpec::Mocks::ExampleMethods` nor does it require `rspec/mocks`.

**Comment by mockdeep** [comment]
@JonRowe how do you restart bootsnap? I did `rm -rf tmp/cache` but I don't see anything else [in their docs](https://github.com/Shopify/bootsnap). Either way, it still fails even after a clean reboot, as well as on our CI machines. Do you have any idea why this would only start happening after an upgrade to 4.0.0?

**Comment by JonRowe** [comment]
We removed a general `require 'rspec/mocks` in favour of a more explicit require to be more compatible with other libraries. If you need rspec mocks you should require it.

**Comment by mockdeep** [comment]
Got it, thanks.
