### ISSUE TITLE
rspec post - wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by jamesla** [rspec/rspec-rails#2320]
## What Ruby, Rails and RSpec versions are you using?

Ruby version:2.5.7p206
Rails version: 6.0.2.2
RSpec version: v4.0.0

I am running rspec-rails 4.0.0 and when I try and use the following methods

```
post "/widgets", :params => '{ "widget": { "name":"My Widget" } }', :headers => nil
```

It throws the exception 

```
An error occurred while loading ./spec/integration/test_spec.rb.
Failure/Error: post "/widgets", :params => '{ "widget": { "name":"My Widget" } }', :headers => nil

ArgumentError:
  wrong number of arguments (given 2, expected 1)
```

A quick search through issue history shows this is an issue that keeps popping up but however has been fixed.

https://github.com/rspec/rspec-rails/issues?q=wrong+number+of+arguments+%28given+2%2C+expected+1%29

However I am running version 4.0.0 of rspec-rails so it should be gone. My gemfile has the entry `  gem 'rspec-rails', '~> 4.0.0'` in it.

Gemfile.lock contains:
```
    rspec-core (3.9.1)
      rspec-support (~> 3.9.1)
    rspec-expectations (3.9.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.9.0)
    rspec-mocks (3.9.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.9.0)
    rspec-rails (4.0.0)
      actionpack (>= 4.2)
      activesupport (>= 4.2)
      railties (>= 4.2)
      rspec-core (~> 3.9)
      rspec-expectations (~> 3.9)
      rspec-mocks (~> 3.9)
      rspec-support (~> 3.9)
    rspec-support (3.9.2)
```

What can I do to fix this?

**Comment by pirj** [comment]
Can you please provide a little bit more details. The most interesting part would be where exactly, which method was supposed to take one argument, but we've passed two.

Do you see the same issue without `params` and `headers`?

**Comment by JonRowe** [comment]
Can you post the stack trace for the error to see where its coming from, and whilst I don't think it's this, what happens if you change `:params =>` and `:headers`: for `params:` and `headers:` (they changed to keyword arguments).

**Comment by jamesla** [comment]
Works fine with just one arugment IE `post '/endpoint'` or `get '/endpoint'`

Here is the stack trace:

```
/home/vagrant/api/spec/login_helper.rb:3:in `get_auth_token'
/home/vagrant/api/spec/integration/gamemode_spec.rb:9:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:387:in `module_exec'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:387:in `subclass'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:260:in `block in define_example_group_method'
/var/lib/gems/2.5.0/gems/rswag-specs-2.3.1/lib/rswag/specs/example_group_helpers.rb:8:in `path'
/home/vagrant/api/spec/integration/gamemode_spec.rb:8:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:387:in `module_exec'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:387:in `subclass'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:260:in `block in define_example_group_method'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/dsl.rb:43:in `block in expose_example_group_alias'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/dsl.rb:84:in `block (2 levels) in expose_example_group_alias_globally'
/home/vagrant/api/spec/integration/gamemode_spec.rb:7:in `<top (required)>'
/var/lib/gems/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/var/lib/gems/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/configuration.rb:2076:in `load_file_handling_errors'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/configuration.rb:1583:in `block in load_spec_files'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/configuration.rb:1581:in `each'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/configuration.rb:1581:in `load_spec_files'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:102:in `setup'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:86:in `run'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:71:in `run'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:45:in `invoke'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/exe/rspec:4:in `<top (required)>'
/usr/local/bin/rspec:23:in `load'
/usr/local/bin/rspec:23:in `<main>'

```

**Comment by pirj** [comment]
Do you mind sharing a piece of code that is around `spec/login_helper.rb:3` and the signature of methods called from that line?

**Comment by JonRowe** [comment]
Was that generated with `--backtrace` on?

**Comment by jamesla** [comment]
```
# spec/login_helper.rb
require "rails_helper"

def get_auth_token
  begin
    post '/login',
      params: { "user": { "email": "test@test.com", "password": "test123" } },
      headers: { 'CONTENT_TYPE' => 'application/json' }
  rescue 
    puts caller 
  end
end
```

**Comment by JonRowe** [comment]
The request methods `post` etc are Rails test helper methods and we don't generally interfere with them, so its odd that you'd get an error if you're passing things as they want.

Rather than `caller`, rescue the exception with `Exception => exception` and `puts exception.backtrace`

**Comment by jamesla** [comment]
```
/var/lib/gems/2.5.0/gems/rswag-specs-2.3.1/lib/rswag/specs/example_group_helpers.rb:12:in `block (2 levels) in <module:ExampleGroupHelpers>'
/home/vagrant/respawn-api/spec/login_helper.rb:5:in `get_auth_token'
/home/vagrant/respawn-api/spec/integration/gamemode_spec.rb:9:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:387:in `module_exec'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:387:in `subclass'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:260:in `block in define_example_group_method'
/var/lib/gems/2.5.0/gems/rswag-specs-2.3.1/lib/rswag/specs/example_group_helpers.rb:8:in `path'
/home/vagrant/respawn-api/spec/integration/gamemode_spec.rb:8:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:387:in `module_exec'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:387:in `subclass'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/example_group.rb:260:in `block in define_example_group_method'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/dsl.rb:43:in `block in expose_example_group_alias'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/dsl.rb:84:in `block (2 levels) in expose_example_group_alias_globally'
/home/vagrant/respawn-api/spec/integration/gamemode_spec.rb:7:in `<top (required)>'
/var/lib/gems/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/var/lib/gems/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/configuration.rb:2076:in `load_file_handling_errors'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/configuration.rb:1583:in `block in load_spec_files'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/configuration.rb:1581:in `each'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/configuration.rb:1581:in `load_spec_files'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:102:in `setup'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:86:in `run'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:71:in `run'
/var/lib/gems/2.5.0/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:45:in `invoke'
```

**Comment by JonRowe** [comment]
`var/lib/gems/2.5.0/gems/rswag-specs-2.3.1/lib/rswag/specs/example_group_helpers.rb:12` looks suspicous?

**Comment by klyonrad** [comment]
[They dynamically define methods with the same name there](https://github.com/rswag/rswag/blob/42fdf6d482b2e5d4aee4f461abf697b2aa9c3894/rswag-specs/lib/rswag/specs/example_group_helpers.rb#L12). That is certainly fancy.

I would suggest to ask the question over there or dive deeper through debugging

```ruby
      [:get, :post, :patch, :put, :delete, :head, :options, :trace].each do |verb|
        define_method(verb) do |summary, &block|
          api_metadata = { operation: { verb: verb, summary: summary } }
          describe(verb, api_metadata, &block)
        end
      end
```

**Comment by pirj** [comment]
> That is certainly fancy.

Exactly.
@jamesla You seem to intend to use Rails' `post` in your `get_auth_token` method, but `rswag`'s DSL seems to be completely different:
```ruby
describe 'Blogs API' do

  path '/blogs' do

    post 'Creates a blog' do
      tags 'Blogs'
      consumes 'application/json'
      parameter name: :blog, in: :body, schema: {
        type: :object,
        properties: {
          title: { type: :string },
          content: { type: :string }
        },
        required: [ 'title', 'content' ]
      }

      response '201', 'blog created' do
        let(:blog) { { title: 'foo', content: 'bar' } }
        run_test!
      end

      response '422', 'invalid request' do
        let(:blog) { { title: 'foo' } }
        run_test!
      end
    end
  end
```

They seem to [inject](https://github.com/rswag/rswag/blob/master/rswag-specs/lib/rswag/specs.rb#L18) their `post` and other helpers for all request specs, and that's kind of weird.

I suggest you play around with requires and only include their helpers where you see fit.

Otherwise, I don't see there's anything to blame `rspec-rails` for, please feel free to reopen the ticket if you think there's something we can address on our side.

**Comment by JonRowe** [comment]
What does your original spec look like? As it looks like somehow you have methods intended to be used at class level at instance level? Do you have an extend somewhere?

**Comment by pirj** [comment]
Well noticed ☝️
