### ISSUE TITLE
ArgumentError: wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by michudzik** [rspec/rspec-rails#2446]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]
Rails version: Rails 6.1.1
RSpec version:
RSpec 3.10
  - rspec-core 3.10.1
  - rspec-expectations 3.10.1
  - rspec-mocks 3.10.1
  - rspec-rails 4.0.2
  - rspec-support 3.10.1

## Steps to reproduce
Test controller:
``` 
class SampleController < ActionController::Base
    layout 'application'

    def new
     sample = Sample.new

      render(:new, locals: { sample: sample })
    end
end
```
Test sample:
```
require 'rails_helper'

RSpec.describe SampleController, type: :controller do
  describe 'GET #new' do
    before { get :new }

    it { expect(response).to be_successful }
    it { expect(response).to render_template(:new) }
  end
end
```
Error:
```
4) SampleController GET #new
     Failure/Error: before { get :new }

     ArgumentError:
       wrong number of arguments (given 2, expected 1)
```
Related issues:
https://github.com/rspec/rspec-rails/issues/2177

I saw that this was fixed for Rails 6.0 but It happens again. Downgrading to `4.0.0.beta3` didn't help

**Comment by JonRowe** [comment]
I think this is a duplicate of #2431 are you using `rails-controller-testing` and have you upgraded it to `1.0.5`?

**Comment by michudzik** [comment]
Oh. I believe that for some reason i have a really old version of `rails-controller-testing`. It may be a duplicate, you are right. I did not see the issue that you have referenced.

I bumped the version up and it started working. Thanks!

**Comment by Rim-777** [comment]
> I think this is a duplicate of #2431 are you using `rails-controller-testing` and have you upgraded it to `1.0.5`?

I have it updated but still have the same issue. Please share if you have any idea.

**Comment by pirj** [comment]
@Rim-777 Please provide a complete backtrace.

**Comment by anhvqle** [comment]
@pirj my `rails-controller-testing` is at `1.0.5` but I keep getting errors in `lib/action_controller/test_case.rb`? Can't figure it out why (I'm using rails 6.1.7.3 and ruby 3.0.6). I have uploaded my `minitest` gem to `5.18.0` and `minitest-reporters` to `1.6.0` but I don't think they are necessary
```
Minitest::UnexpectedError:         ArgumentError: wrong number of arguments (given 2, expected 1)
            actionpack (6.1.7.3) lib/action_controller/test_case.rb:397:in `get'
            test/functional/concerns/o_auth_filters_test.rb:317:in `block in get'
            actionpack (6.1.7.3) lib/action_dispatch/testing/assertions/routing.rb:174:in `with_routing'
            test/functional/concerns/o_auth_filters_test.rb:312:in `get'
            test/functional/concerns/o_auth_filters_test.rb:174:in `block (3 levels) in <class:OAuthFiltersTest>'
            test/functional/concerns/o_auth_filters_test.rb:179:in `instance_exec'
            test/functional/concerns/o_auth_filters_test.rb:179:in `block in create_test_from_should_hash'
            minitest (5.14.4) lib/minitest/test.rb:98:in `block (3 levels) in run'
            minitest (5.14.4) lib/minitest/test.rb:195:in `capture_exceptions'
            minitest (5.14.4) lib/minitest/test.rb:95:in `block (2 levels) in run'
            minitest (5.14.4) lib/minitest.rb:272:in `time_it'
            minitest (5.14.4) lib/minitest/test.rb:94:in `block in run'
            minitest (5.14.4) lib/minitest.rb:367:in `on_signal'
            minitest (5.14.4) lib/minitest/test.rb:211:in `with_info_handler'
            minitest (5.14.4) lib/minitest/test.rb:93:in `run'
            minitest-reporters (1.4.3) lib/minitest/reporters.rb:48:in `run_with_hooks'
            minitest (5.14.4) lib/minitest.rb:1029:in `run_one_method'
            minitest (5.14.4) lib/minitest.rb:341:in `run_one_method'
            minitest (5.14.4) lib/minitest.rb:328:in `block (2 levels) in run'
            minitest (5.14.4) lib/minitest.rb:327:in `each'
            minitest (5.14.4) lib/minitest.rb:327:in `block in run'
            minitest (5.14.4) lib/minitest.rb:367:in `on_signal'
            minitest (5.14.4) lib/minitest.rb:354:in `with_info_handler'
            minitest (5.14.4) lib/minitest.rb:326:in `run'
            railties (6.1.7.3) lib/rails/test_unit/line_filtering.rb:10:in `run'
            minitest (5.14.4) lib/minitest.rb:164:in `block in __run'
            minitest (5.14.4) lib/minitest.rb:164:in `map'
            minitest (5.14.4) lib/minitest.rb:164:in `__run'
            minitest (5.14.4) lib/minitest.rb:141:in `run'
            minitest (5.14.4) lib/minitest.rb:68:in `block in autorun'
```

**Comment by anhvqle** [comment]
Was able to resolve my issue above. For anyone still running into this issue, if you have a code block calling `super`, you should try something like this: 
```
def get(...)
    # existing code ...

    super(...)
end
```
