### ISSUE TITLE
aggregate_failures with assert_select

### ISSUE THREAD

**Issue by woto** [rspec/rspec-rails#2482]
Hi! It seems that `aggregate_failures` doesn't work with `assert_select`? Or I am doing something wrong?
*crosspost from google groups https://groups.google.com/g/rspec/c/4Xj5BatQyjk

### Your environment
* Ruby version: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
* rspec-core version: rspec-core-3.9.3

### Steps to reproduce

```
aggregate_failures do
  expect(true).to eq(false)
  expect(true).to eq(nil)
end
```

returns

```
0.1) Failure/Error: expect(true).to eq(false)

            expected: false
                 got: true

            (compared using ==)

            Diff:
            @@ -1 +1 @@
            -false
            +true
          # ./spec/requests/tables/news_controller_spec.rb:63:in `block (5 levels) in <top (required)>'

     0.2) Failure/Error: expect(true).to eq(nil)

            expected: nil
                 got: true

            (compared using ==)
          # ./spec/requests/tables/news_controller_spec.rb:64:in `block (5 levels) in <top (required)>'
```

but

```
aggregate_failures do
  assert_select 'h1', 'Newss'
  assert_select 'h2', count: 4
end
```

returns only:

```
Minitest::Assertion: <Newss> expected but was
<News>..
Expected 0 to be >= 1.

  0) Tables::NewsController#index with follow_redirect! has correct title
     Failure/Error: assert_select 'h1', 'Newss'

     Minitest::Assertion:
       <Newss> expected but was
       <News>..
       Expected 0 to be >= 1.
     # ./spec/requests/tables/news_controller_spec.rb:63:in `block (5 levels) in <top (required)>'
```

Any thoughts? thank you

**Comment by woto** [comment]
Ok, thank you for detailed answer. Kind regards
