### ISSUE TITLE
Rspec/Rails System Test Error on JRuby - no superclass method `after_teardown'

### ISSUE THREAD

**Issue by hmistry** [rspec/rspec-rails#2499]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: jruby 9.2.15.0
Rails version: 5.1.7
RSpec version: 3.9.3

## Observed behaviour

I recently converted an app from MRI 2.6.5 to JRuby 9.2.15. All my system tests that were passing in MRI, are now failing with the error below with full backtrace. All these system tests pass if I switch back to MRI 2.6.5 and everything else is more or less the same (Rspec is 3.9.1 when using MRI 2.6.5). 

Not sure if this is a bug with RSpec, Rails, JRuby or is there something I can do on my end to fix it?

```shell
   Failure/Error: Unable to find org/jruby/RubyBasicObject.java to read failed line

   NoMethodError:
     super: no superclass method `after_teardown' for #<RSpec::ExampleGroups::SignIn::SignInPage:0x2a46f079>
     Did you mean?  after_setup



   # org/jruby/RubyBasicObject.java:1715:in `method_missing'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-expectations-3.9.4/lib/rspec/matchers.rb:963:in `method_missing'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:764:in `method_missing'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/actionpack-5.1.7/lib/action_dispatch/testing/assertions/routing.rb:175:in `method_missing'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/actionpack-5.1.7/lib/action_dispatch/testing/integration.rb:398:in `method_missing'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/actionpack-5.1.7/lib/action_dispatch/system_testing/test_helpers/setup_and_teardown.rb:20:in `after_teardown'
   # org/jruby/RubyMethod.java:115:in `call'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-rails-3.9.1/lib/rspec/rails/example/system_example_group.rb:98:in `block in SystemExampleGroup'
   # org/jruby/RubyBasicObject.java:2694:in `instance_exec'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:455:in `instance_exec'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:372:in `run'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:529:in `block in run_owned_hooks_for'
   # org/jruby/RubyArray.java:1809:in `each'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:528:in `run_owned_hooks_for'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:615:in `block in run_example_hooks_for'
   # org/jruby/RubyArray.java:1809:in `each'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:614:in `run_example_hooks_for'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:485:in `run'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:515:in `run_after_example'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:281:in `block in run'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:508:in `block in with_around_and_singleton_context_hooks'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:465:in `block in with_around_example_hooks'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:486:in `block in run'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:350:in `call'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-rails-3.9.1/lib/rspec/rails/adapters.rb:127:in `block in MinitestLifecycleAdapter'
   # org/jruby/RubyBasicObject.java:2694:in `instance_exec'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:455:in `instance_exec'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:390:in `execute_with'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:628:in `block in run_around_example_hooks_for'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:350:in `call'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:627:in `run_around_example_hooks_for'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:486:in `run'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:465:in `with_around_example_hooks'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:508:in `with_around_and_singleton_context_hooks'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:259:in `run'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:644:in `block in run_examples'
   # org/jruby/RubyArray.java:2577:in `map'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:640:in `run_examples'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:606:in `run'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:607:in `block in run'
   # org/jruby/RubyArray.java:2577:in `map'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:607:in `run'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:121:in `block in run_specs'
   # org/jruby/RubyArray.java:2577:in `map'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:121:in `block in run_specs'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/configuration.rb:2061:in `with_suite_hooks'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:116:in `block in run_specs'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/reporter.rb:74:in `report'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:115:in `run_specs'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:89:in `run'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:71:in `run'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:45:in `invoke'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/gems/rspec-core-3.9.3/exe/rspec:4:in `<main>'
   # org/jruby/RubyKernel.java:1009:in `load'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/bin/rspec:23:in `<main>'
   # org/jruby/RubyKernel.java:1048:in `eval'
   # /Users/hm/.rvm/gems/jruby-9.2.15.0@abc/bin/jruby_executable_hooks:22:in `<main>'
```

## Expected behaviour

System tests should pass on JRuby like it does with MRI.

## Can you provide an example app?

See my comment below for sample code.

**Comment by benoittgt** [comment]
Hello @hmistry 

Could you provide a small reproduction example? At least the test you wrote?

Thanks

**Comment by hmistry** [comment]
Hi @benoittgt 

Here's sample code that reproduces the error.

#### Sample app code
```ruby
# Gemfile
gem 'rails', '~> 5.1.7'
gem 'mysql2', platform: :ruby
gem 'activerecord-jdbcmysql-adapter', platform: :jruby
gem 'puma'

group :development, :test do
  gem 'rspec-rails', '3.9.1'
end

group :test do
  gem 'capybara', '3.35.3'
  gem 'selenium-webdriver'
  gem 'webdrivers', '4.5.0'
end
```
```ruby
# config/routes.rb
Rails.application.routes.draw do
  resources :cars
end
```
```ruby
# model/car.rb
class Car < ApplicationRecord
end
```
```ruby
# db/schema.rb
ActiveRecord::Schema.define(version: 20210309012108) do
  create_table "cars", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8" do |t|
    t.string "name"
    t.integer "year"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
end
```
```ruby
# controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end
end
```
```erb
# view/cars/index.html.erb
<h1>Cars</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.name %></td>
        <td><%= car.year %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Car', new_car_path %>
```
```ruby
# spec/system/cars_spec.rb
require 'rails_helper'

RSpec.describe "Cars", type: :system do
  before do
    driven_by(:selenium)
    visit "/cars"
  end

  it "has Cars header, name and Year" do
    expect(page).to have_text "Cars"
    expect(page).to have_text "Name"
    expect(page).to have_text "Year"
  end

  it "has New Car link" do
    expect(page).to have_link "New Car", href: "/cars/new"
  end
end
```

#### Results
```shell
# Using MRI 2.6.5 -> Passes
$ rspec spec
..

Finished in 3.8 seconds (files took 2.81 seconds to load)
2 examples, 0 failures
```
```shell
# Using JRuby 9.2.15.0 -> Fails
$ ruby -v
jruby 9.2.15.0 (2.5.7) 2021-02-24 aa05fda562 Java HotSpot(TM) 64-Bit Server VM 15+36-1562 on 15+36-1562 +jit [darwin-x86_64]

$ rspec spec
FF

Failures:

  1) Cars has Cars header, name and Year
     Failure/Error: Unable to find org/jruby/RubyBasicObject.java to read failed line

     NoMethodError:
       super: no superclass method `after_teardown` for #<RSpec::ExampleGroups::Cars:0x3152d449>
       Did you mean?  after_setup



     # org/jruby/RubyBasicObject.java:1715:in `method_missing`
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-expectations-3.9.4/lib/rspec/matchers.rb:963:in `method_missing`
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:764:in `method_missing`
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/actionpack-5.1.7/lib/action_dispatch/testing/assertions/routing.rb:175:in `method_missing`
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/actionpack-5.1.7/lib/action_dispatch/testing/integration.rb:398:in `method_missing`
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/actionpack-5.1.7/lib/action_dispatch/system_testing/test_helpers/setup_and_teardown.rb:20:in `after_teardown`
     # org/jruby/RubyMethod.java:115:in `call'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-rails-3.9.1/lib/rspec/rails/example/system_example_group.rb:98:in `block in SystemExampleGroup'
     # org/jruby/RubyBasicObject.java:2694:in `instance_exec'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:455:in `instance_exec'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:372:in `run'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:529:in `block in run_owned_hooks_for'
     # org/jruby/RubyArray.java:1809:in `each'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:528:in `run_owned_hooks_for'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:615:in `block in run_example_hooks_for'
     # org/jruby/RubyArray.java:1809:in `each'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:614:in `run_example_hooks_for'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:485:in `run'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:515:in `run_after_example'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:281:in `block in run'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:508:in `block in with_around_and_singleton_context_hooks'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:465:in `block in with_around_example_hooks'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:486:in `block in run'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:350:in `call'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-rails-3.9.1/lib/rspec/rails/adapters.rb:127:in `block in MinitestLifecycleAdapter'
     # org/jruby/RubyBasicObject.java:2694:in `instance_exec'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:455:in `instance_exec'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:628:in `block in run_around_example_hooks_for'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:350:in `call'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:627:in `run_around_example_hooks_for'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:486:in `run'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:465:in `with_around_example_hooks'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:508:in `with_around_and_singleton_context_hooks'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:259:in `run'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:644:in `block in run_examples'
     # org/jruby/RubyArray.java:2577:in `map'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:640:in `run_examples'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:606:in `run'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:121:in `block in run_specs'
     # org/jruby/RubyArray.java:2577:in `map'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:121:in `block in run_specs'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/configuration.rb:2061:in `with_suite_hooks'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/reporter.rb:74:in `report'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:115:in `run_specs'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:89:in `run'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:71:in `run'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/exe/rspec:4:in `<main>'
     # org/jruby/RubyKernel.java:1009:in `load'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/bin/rspec:23:in `<main>'
     # org/jruby/RubyKernel.java:1048:in `eval'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/bin/jruby_executable_hooks:22:in `<main>'
     #
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.

  2) Cars has New Car link
     Failure/Error: Unable to find org/jruby/RubyBasicObject.java to read failed line

     NoMethodError:
       super: no superclass method `after_teardown` for #<RSpec::ExampleGroups::Cars:0x3e7c66b3>
       Did you mean?  after_setup



     # org/jruby/RubyBasicObject.java:1715:in `method_missing`
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-expectations-3.9.4/lib/rspec/matchers.rb:963:in `method_missing`
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:764:in `method_missing`
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/actionpack-5.1.7/lib/action_dispatch/testing/assertions/routing.rb:175:in `method_missing`
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/actionpack-5.1.7/lib/action_dispatch/testing/integration.rb:398:in `method_missing`
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/actionpack-5.1.7/lib/action_dispatch/system_testing/test_helpers/setup_and_teardown.rb:20:in `after_teardown`
     # org/jruby/RubyMethod.java:115:in `call'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-rails-3.9.1/lib/rspec/rails/example/system_example_group.rb:98:in `block in SystemExampleGroup'
     # org/jruby/RubyBasicObject.java:2694:in `instance_exec'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:455:in `instance_exec'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:372:in `run'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:529:in `block in run_owned_hooks_for'
     # org/jruby/RubyArray.java:1809:in `each'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:528:in `run_owned_hooks_for'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:615:in `block in run_example_hooks_for'
     # org/jruby/RubyArray.java:1809:in `each'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:614:in `run_example_hooks_for'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:485:in `run'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:515:in `run_after_example'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:281:in `block in run'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:508:in `block in with_around_and_singleton_context_hooks'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:465:in `block in with_around_example_hooks'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:486:in `block in run'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:350:in `call'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-rails-3.9.1/lib/rspec/rails/adapters.rb:127:in `block in MinitestLifecycleAdapter'
     # org/jruby/RubyBasicObject.java:2694:in `instance_exec'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:455:in `instance_exec'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:628:in `block in run_around_example_hooks_for'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:350:in `call'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:627:in `run_around_example_hooks_for'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:486:in `run'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:465:in `with_around_example_hooks'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:508:in `with_around_and_singleton_context_hooks'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:259:in `run'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:644:in `block in run_examples'
     # org/jruby/RubyArray.java:2577:in `map'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:640:in `run_examples'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:606:in `run'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:121:in `block in run_specs'
     # org/jruby/RubyArray.java:2577:in `map'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:121:in `block in run_specs'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/configuration.rb:2061:in `with_suite_hooks'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/reporter.rb:74:in `report'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:115:in `run_specs'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:89:in `run'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:71:in `run'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/gems/rspec-core-3.9.3/exe/rspec:4:in `<main>'
     # org/jruby/RubyKernel.java:1009:in `load'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/bin/rspec:23:in `<main>'
     # org/jruby/RubyKernel.java:1048:in `eval'
     # /Users/hm/.rvm/gems/jruby-9.2.15.0@rubber/bin/jruby_executable_hooks:22:in `<main>'
     #
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.

Finished in 3.69 seconds (files took 6.71 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/system/cars_spec.rb:9 # Cars has Cars header, name and Year
rspec ./spec/system/cars_spec.rb:15 # Cars has New Car link

```

**Comment by pirj** [comment]
Did you happen to find a way around this? I'd suggest opening a ticket for JRuby.
There's most probably nothing we can do on our side.

**Comment by hmistry** [comment]
@pirj Hi. I did not find a solution and was hoping for insights or clues from the team here.

I'd like to request that you re-open this issue because system tests in Rails is a very useful functionality that is not working whether it is on JRuby or Rspec side. Other dev's should know about it and be able to find it in the open issues list. Also it would be good thing for you when testing Rspec compatibility with JRuby to know if it is still broken or fixed. 

I understand you might feel like there's nothing you can do as I too felt same way when trying to root cause it but if it's open, then some one with more expertise might know how to fix it but closing the issue will guarantee no one will look into it.

cc @headius Do you have any thoughts from the backtrace whether this could be a Jruby or Rspec issue?

**Comment by pirj** [comment]
Would you please to open a PR with a failing spec? It should be a good start.

**Comment by JonRowe** [comment]
@hmistry You provided a sample app, thanks, but could you try creating a scenario we could add to our tests? None of us use JRuby locally

**Comment by hmistry** [comment]
@JonRowe Ok I'll try to create a test scenario to reproduce the error in JRuby. I'll ask if I have questions. Thank you for reopening this issue so that we may find a solution. 🙏

**Comment by pirj** [comment]
Closing as stale.
