### ISSUE TITLE
undefined method `driver_path=' for Selenium::WebDriver::Chrome:Module

### ISSUE THREAD

**Issue by hamzaiqbal12345** [rspec/rspec-rails#2616]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 2.7.1
Rails version: 5.2.0
RSpec version: 5.1.2

## Observed behaviour
```
An error occurred while loading ./spec/models/student_spec.rb.
Failure/Error: require_relative '../config/environment'

NoMethodError:
  undefined method `driver_path=' for Selenium::WebDriver::Chrome:Module
 /Users/dev/.rvm/gems/ruby-2.7.1/gems/chromedriver-helper-2.1.1/lib/chromedriver-helper.rb:4:in `<main>'
 /Users/dev/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
 /Users/dev/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
 ./config/application.rb:7:in `<top (required)>'
 ./config/environment.rb:2:in `require_relative'
 ./config/environment.rb:2:in `<top (required)>'
 ./spec/rails_helper.rb:4:in `require_relative'
 ./spec/rails_helper.rb:4:in `<top (required)>'
 ./spec/models/student_spec.rb:1:in `require'
 ./spec/models/student_spec.rb:1:in `<top (required)>'

An error occurred while loading ./spec/requests/students_spec.rb.
Failure/Error: require_relative '../config/environment'

NoMethodError:
  undefined method `driver_path=' for Selenium::WebDriver::Chrome:Module
 /Users/dev/.rvm/gems/ruby-2.7.1/gems/chromedriver-helper-2.1.1/lib/chromedriver-helper.rb:4:in `<main>'
 /Users/dev/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
 /Users/dev/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
 ./config/application.rb:7:in `<main>'
 ./config/environment.rb:2:in `require_relative'
 ./config/environment.rb:2:in `<main>'
 ./spec/rails_helper.rb:4:in `require_relative'
 ./spec/rails_helper.rb:4:in `<main>'
 /Users/dev/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
 /Users/dev/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
 ./spec/requests/students_spec.rb:1:in `<main>'
No examples found.


Finished in 0.00005 seconds (files took 0.72024 seconds to load)
0 examples, 0 failures, 2 errors occurred outside of examples
```

## Expected behaviour

the tests should run.

**Comment by JonRowe** [comment]
Closing because`driver_path` is not an RSpec::Rails method, this seems like a selenium / capybara issue.
