### ISSUE TITLE
#helper method returns nil in helper spec [rails 3.1]

### ISSUE THREAD

**Issue by mlapshin** [rspec/rspec-rails#441]
I have a helper spec like following:

``` ruby
require "spec_helper"

describe UsersHelper do
  before(:each) do
    @user  = User.make!
  end

  describe "#link_to_user" do
    html = self.helper.link_to_user(@user)

    html.should include(@user.nickname)
    html.should include(user_path(@user))
  end
end
```

And this spec fails with following error:

```
/home/sotakone/.rvm/gems/ruby-1.9.2-p180@global/gems/activesupport-3.1.0/lib/active_support/whiny_nil.rb:48:in `method_missing': undefined method `link_to_user' for nil:NilClass (NoMethodError)
    from /home/sotakone/work/weedburg/spec/helpers/users_helper_spec.rb:9:in `block (2 levels) in <top (required)>'
    from /home/sotakone/.rvm/gems/ruby-1.9.2-p180@global/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:142:in `module_eval'
    from /home/sotakone/.rvm/gems/ruby-1.9.2-p180@global/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:142:in `subclass'
    from /home/sotakone/.rvm/gems/ruby-1.9.2-p180@global/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:129:in `describe'
    from /home/sotakone/work/weedburg/spec/helpers/users_helper_spec.rb:8:in `block in <top (required)>'
    from /home/sotakone/.rvm/gems/ruby-1.9.2-p180@global/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:142:in `module_eval'
    from /home/sotakone/.rvm/gems/ruby-1.9.2-p180@global/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:142:in `subclass'
    from /home/sotakone/.rvm/gems/ruby-1.9.2-p180@global/gems/rspec-core-2.6.4/lib/rspec/core/example_group.rb:129:in `describe'
    from /home/sotakone/.rvm/gems/ruby-1.9.2-p180@global/gems/rspec-core-2.6.4/lib/rspec/core/dsl.rb:5:in `describe'
    from /home/sotakone/work/weedburg/spec/helpers/users_helper_spec.rb:3:in `<top (required)>'
    from /home/sotakone/.rvm/gems/ruby-1.9.2-p180@global/gems/rspec-core-2.6.4/lib/rspec/core/configuration.rb:419:in `load'
    from /home/sotakone/.rvm/gems/ruby-1.9.2-p180@global/gems/rspec-core-2.6.4/lib/rspec/core/configuration.rb:419:in `block in load_spec_files'
    from /home/sotakone/.rvm/gems/ruby-1.9.2-p180@global/gems/rspec-core-2.6.4/lib/rspec/core/configuration.rb:419:in `map'
    from /home/sotakone/.rvm/gems/ruby-1.9.2-p180@global/gems/rspec-core-2.6.4/lib/rspec/core/configuration.rb:419:in `load_spec_files'
    from /home/sotakone/.rvm/gems/ruby-1.9.2-p180@global/gems/rspec-core-2.6.4/lib/rspec/core/command_line.rb:18:in `run'
    from /home/sotakone/.rvm/gems/ruby-1.9.2-p180@global/gems/rspec-core-2.6.4/lib/rspec/core/runner.rb:80:in `run_in_process'
    from /home/sotakone/.rvm/gems/ruby-1.9.2-p180@global/gems/rspec-core-2.6.4/lib/rspec/core/runner.rb:69:in `run'
    from /home/sotakone/.rvm/gems/ruby-1.9.2-p180@global/gems/rspec-core-2.6.4/lib/rspec/core/runner.rb:11:in `block in autorun'
```

I'm using rspec-rails 2.6.1 and rails 3.1.0.

**Comment by wwilkins** [comment]
Thanks for making it public because I just googled for this issue having made the same mistake!
