### ISSUE TITLE
Adding routes using with_routing has no effect and results in ActionController::RoutingError

### ISSUE THREAD

**Issue by TylerRick** [rspec/rspec-rails#817]
I expected all of these examples to pass:

```ruby
require 'spec_helper'

class SubclassController < ApplicationController
  def test
    render text: 'ok'
  end
end

describe SubclassController do
  def skip_routing
    with_routing do |map|
      map.draw do
        # I've tried both of these versions:
        match ':controller/:action'
        #get 'subclass/:action' => 'subclass'
      end
      yield
    end
  end

  # This passes.
  specify do
    skip_routing do
      expect(get: '/subclass/test').to route_to("subclass#test")
    end
  end

  # This fails. Why?
  specify do
    skip_routing do
      get :test
      response.body.should == 'ok'
    end
  end
end
```

But one of them fails:

```
  1) SubclassController 
     Failure/Error: get :test
     ActionController::RoutingError:
       No route matches {:controller=>"subclass", :action=>"test"}
     # ./spec/controllers/application_controller_spec.skip_routing.rb:33:in `block (3 levels) in <top (required)>'
     # ./spec/controllers/application_controller_spec.skip_routing.rb:19:in `block in skip_routing'
     # ./spec/controllers/application_controller_spec.skip_routing.rb:13:in `skip_routing'
     # ./spec/controllers/application_controller_spec.skip_routing.rb:32:in `block (2 levels) in <top (required)>'
     # -e:1:in `<main>'
```

How can I get it to recognize the route added with `with_routing`?

**Comment by jbielick** [comment]
This seems to still be an issue in `rspec-rails-3.2.1`

**Comment by hamzakc** [comment]
Just ran into this problem as well. On rspec-rails-3.3.3

**Comment by samphippen** [comment]
@cupakromer is this still valid?

**Comment by samphippen** [comment]
Closing in favour of #1652
