### ISSUE TITLE
render_views is not working in latest

### ISSUE THREAD

**Issue by justin808** [rspec/rspec-rails#932]
I just synched up with the latest versions and I get this message

```
undefined local variable or method `render_views
```

Any advice?

```
rspec spec/controllers/registrations_controller_spec.rb                                                                                                                                                                     ✹ ✚ [16:22:06]
Loading environment test
WARNING: VCR's FakeWeb integration is deprecated and will be removed in VCR 3.0.
/Users/justin/j/blink/bpos/spec/controllers/registrations_controller_spec.rb:5:in `block in <top (required)>': undefined local variable or method `render_views' for RSpec::ExampleGroups::UsersRegistrationsController:Class (NameError)
    from /Users/justin/.rvm/gems/ruby-2.0.0-p353@rails4/gems/rspec-core-3.0.0.beta1/lib/rspec/core/example_group.rb:253:in `module_eval'
    from /Users/justin/.rvm/gems/ruby-2.0.0-p353@rails4/gems/rspec-core-3.0.0.beta1/lib/rspec/core/example_group.rb:253:in `subclass'
    from /Users/justin/.rvm/gems/ruby-2.0.0-p353@rails4/gems/rspec-core-3.0.0.beta1/lib/rspec/core/example_group.rb:239:in `describe'
    from /Users/justin/.rvm/gems/ruby-2.0.0-p353@rails4/gems/rspec-core-3.0.0.beta1/lib/rspec/core/dsl.rb:18:in `describe'
    from /Users/justin/j/blink/bpos/spec/controllers/registrations_controller_spec.rb:4:in `<top (required)>'
    from /Users/justin/.rvm/gems/ruby-2.0.0-p353@rails4/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
    from /Users/justin/.rvm/gems/ruby-2.0.0-p353@rails4/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `block in load'
    from /Users/justin/.rvm/gems/ruby-2.0.0-p353@rails4/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
    from /Users/justin/.rvm/gems/ruby-2.0.0-p353@rails4/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
    from /Users/justin/.rvm/gems/ruby-2.0.0-p353@rails4/gems/rspec-core-3.0.0.beta1/lib/rspec/core/configuration.rb:886:in `block in load_spec_files'
    from /Users/justin/.rvm/gems/ruby-2.0.0-p353@rails4/gems/rspec-core-3.0.0.beta1/lib/rspec/core/configuration.rb:886:in `each'
    from /Users/justin/.rvm/gems/ruby-2.0.0-p353@rails4/gems/rspec-core-3.0.0.beta1/lib/rspec/core/configuration.rb:886:in `load_spec_files'
    from /Users/justin/.rvm/gems/ruby-2.0.0-p353@rails4/gems/rspec-core-3.0.0.beta1/lib/rspec/core/command_line.rb:22:in `run'
    from /Users/justin/.rvm/gems/ruby-2.0.0-p353@rails4/gems/rspec-core-3.0.0.beta1/lib/rspec/core/runner.rb:90:in `run'
    from /Users/justin/.rvm/gems/ruby-2.0.0-p353@rails4/gems/rspec-core-3.0.0.beta1/lib/rspec/core/runner.rb:17:in `block in autorun'
```

gem versions:

```
    rspec (3.0.0.beta1)
      rspec-core (= 3.0.0.beta1)
      rspec-expectations (= 3.0.0.beta1)
      rspec-mocks (= 3.0.0.beta1)
    rspec-collection_matchers (0.0.2)
      rspec-expectations (>= 2.99.0.beta1)
    rspec-core (3.0.0.beta1)
      rspec-support (= 3.0.0.beta1)
    rspec-expectations (3.0.0.beta1)
      diff-lcs (>= 1.1.3, < 2.0)
      rspec-support (= 3.0.0.beta1)
    rspec-instafail (0.2.4)
    rspec-its (1.0.0)
      rspec-core (>= 2.99.0.beta1)
      rspec-expectations (>= 2.99.0.beta1)
    rspec-mocks (3.0.0.beta1)
      rspec-support (= 3.0.0.beta1)
    rspec-rails (3.0.0.beta1)
      actionpack (>= 3.0)
      activemodel (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-collection_matchers
      rspec-core (= 3.0.0.beta1)
      rspec-expectations (= 3.0.0.beta1)
      rspec-mocks (= 3.0.0.beta1)
    rspec-retry (0.2.1)
      rspec
    rspec-support (3.0.0.beta1)
```

**Comment by AJFaraday** [comment]
I've just experienced this issue on a Rails 3.2 repo, and found another possible cause.

The issue was that the controller specs had been placed in `spec/controller`, they were not recognised as controller specs. 

I fixed it by renaming the folder `spec/controllers`.

------------------

Found with these Rspec and related gem versions:

```
    rspec (2.14.1)
      rspec-core (~> 2.14.0)
      rspec-expectations (~> 2.14.0)
      rspec-mocks (~> 2.14.0)
    rspec-core (2.14.5)
    rspec-expectations (2.14.5)
      diff-lcs (>= 1.1.3, < 2.0)
    rspec-mocks (2.14.6)
    rspec-rails (2.14.2)
      actionpack (>= 3.0)
      activemodel (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 2.14.0)
      rspec-expectations (~> 2.14.0)
      rspec-mocks (~> 2.14.0)
```

**Comment by samphippen** [comment]
hi @AJFaraday, your cause is unrelated to the root of this issue. honestly I'm pretty sure this is solved

**Comment by samphippen** [comment]
I'm locking the conversation thread here, if anyone encounters something related, please open a new issue so that we can attempt to reproduce there.
