### ISSUE TITLE
Rails 4.1.0.rc1 no longer defines db:test:prepare

### ISSUE THREAD

**Issue by joshuaflanagan** [rspec/rspec-rails#936]
See https://github.com/rails/rails/pull/13528

Create a Rails 4.1.0.rc1 project _without_ test-unit support:

``` shell
rails new foo -T
```

Add rspec-rails (2.14.1) to the Gemfile, bundle, `rails g rspec:install`. Then try to run specs:

``` shell
> rake spec
rake aborted!
Don't know how to build task 'test:prepare'
```

This line will likely need a version check:
https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/tasks/rspec.rake#L6

**Comment by UsmanMalik** [comment]
Not working for me

Rails 5 

Rakefile
```

# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'

Rails.application.load_tasks


task 'payment:email_admin_subscription_payment'

```
```
{ 47231767519260 rufus-scheduler intercepted an error:
  47231767519260   job:
  47231767519260     Rufus::Scheduler::EveryJob "1m" {}
  47231767519260   error:
  47231767519260     47231767519260
  47231767519260     RuntimeError
  47231767519260     Don't know how to build task 'payment:email_admin_subscription_payment' (see --tasks)
  47231767519260       /home/usman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task_manager.rb:58:in `[]'
  47231767519260       /home/usman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:361:in `[]'
  47231767519260       /home/usman/projects/new_kidal/config/initializers/scheduler.rb:13:in `block in <top (required)>'
  47231767519260       /home/usman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.3.3/lib/rufus/scheduler/jobs.rb:234:in `do_call'
  47231767519260       /home/usman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.3.3/lib/rufus/scheduler/jobs.rb:278:in `trigger_now'
  47231767519260       /home/usman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.3.3/lib/rufus/scheduler/jobs.rb:320:in `block (3 levels) in start_work_thread'
  47231767519260       /home/usman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.3.3/lib/rufus/scheduler/jobs.rb:323:in `block (2 levels) in start_work_thread'
  47231767519260       /home/usman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.3.3/lib/rufus/scheduler/jobs.rb:309:in `loop'
  47231767519260       /home/usman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rufus-scheduler-3.3.3/lib/rufus/scheduler/jobs.rb:309:in `block in start_work_thread'
  47231767519260   tz:
  47231767519260     ENV['TZ']: 
  47231767519260     Time.now: 2017-02-14 22:52:52 +0500
  47231767519260     local_tzone: #<TZInfo::DataTimezone: Etc/UTC>
  47231767519260   scheduler:
  47231767519260     object_id: 47231785373960
  47231767519260     opts:
  47231767519260       {}
  47231767519260       frequency: 0.3
  47231767519260       scheduler_lock: #<Rufus::Scheduler::NullLock:0x0055ea0392acf0>
  47231767519260       trigger_lock: #<Rufus::Scheduler::NullLock:0x0055ea0392acc8>
  47231767519260     uptime: 60.0498480796814 (1m49)
  47231767519260     down?: false
  47231767519260     threads: 2
  47231767519260       thread: #<Thread:0x0055ea0392ac00>
  47231767519260       thread_key: rufus_scheduler_47231785373960
  47231767519260       work_threads: 1
  47231767519260         active: 1
  47231767519260         vacant: 0
  47231767519260         max_work_threads: 28
  47231767519260       mutexes: {}
  47231767519260     jobs: 1
  47231767519260       at_jobs: 0
  47231767519260       in_jobs: 0
  47231767519260       every_jobs: 1
  47231767519260       interval_jobs: 0
  47231767519260       cron_jobs: 0
  47231767519260     running_jobs: 1
  47231767519260     work_queue: 0
} 47231767519260 .
```



require 'rake'

require 'rufus-scheduler'

scheduler = Rufus::Scheduler::singleton

# jobs go below here.

scheduler.every '1m' do
  # do stuff
  Rails.logger.info "hello, it's #{Time.now}"
  # rake "payment_check_email:payment_check"
  Rake::Task["payment:email_admin_subscription_payment"].invoke
  # rake "notify:user"
end

```
```

**Comment by JonRowe** [comment]
@UsmanMalik I think you might have pasted that in the wrong place, that has nothing to do with RSpec but is down to your rake setup for whatever rufus is.
